eclipse-pass/pass-ui

app/models/submission.js
app/routes/application.js

updated submission model to include grants. updated test objects to reflect this change.

Model update

---

app/components/find-grant.js
app/components/submission-funding-table.js
app/components/workflow-group.js
app/controllers/submission/show/funding.js
app/routes/application.js
app/routes/submission/show.js
app/routes/submission/show/funding.js
app/styles/app.scss
app/templates/components/find-grant.hbs
app/templates/components/submission-funding-table.hbs
app/templates/submission/show/funding.hbs
app/templates/submission/show/index.hbs
package-lock.json
package.json
tests/integration/components/find-grant-test.js
tests/integration/components/submission-funding-table-test.js
tests/unit/controllers/submission/show/funding-test.js

* Provides a 'funders' workflow step
* UI widget to search and add funding source(s) to submission
The submissions table(s) never show funding source for submissions; I don't know why
2.  Create a branch from master to try it out in : `git checkout -b birkland-issue-17 master`
3.  Pull the PR into it `git pull https://github.com/birkland/pass-ember.git issue-17`
* From grants table
1. Create new submission (feel free to give it a DOI, or not; a title) and click save and continue
2. It should show an overview summary.  Click `next`, or `funding` from the sidebar
3. You should see the grant you started from in the funding
4. …

Add grants in 'funders' submission workflow step

---

app/controllers/submission/show/submission.js
app/templates/submission/show/submission.hbs
tests/unit/controllers/submission/show/submission-test.js

2.  Create a branch from master to try it out in : `git checkout -b birkland-issue-50 master`
3.  Pull the PR into it `git pull https://github.com/birkland/pass-ember.git issue-50`
* Look at the submission button
1. Create a new submission (i.e. go to `http://localhost:4200/submission/`, or visit the grants or submission table)
2. Just click past the initial DOI/Title/Journal stuff.  Save and continue
3. Click on the 'submission' button on the navigation bar.
Resolves #50

Add submission button skeleton

---

app/templates/components/submission-metadata-common.hbs

* Added UI elements to the Common Metadata page according to wireframe
* Included journal's Volume and Issue field
Interested parties @birkland
Resolves #56

Laid out  UI elements doe common metadata page

---

app/templates/components/submission-metadata-par.hbs

* Added acknowledgement check box - the only input element needed for PAR
Interested parties @birkland
Resolves #59

added UI elements for PAR metadata page

---

app/templates/components/submission-metadata-nihms.hbs

* The NIHMS metadata forms is laid out MOSTly according to wireframe. some repeating groups of input elements may need to be renamed. 
Interested parties @birkland
Resolves #58

Issue 58 - Laying out the web form for NIHMS metadata

---

app/templates/components/submission-nav.hbs
app/templates/submission/show/funding.hbs

* Change text for "Funders" and "Funding" to "Awards" in template files. 
* Did not change the name of the underlying elements deeper in the code. If that's desired, leave me a comment, I'll make a ticket for that to be done later. 
Interested parties @birkland
Resolves #60

Changed Funders/Funding nav and headers to Awards

---

app/templates/components/submission-metadata-common.hbs
app/templates/components/submission-metadata-nihms.hbs
app/templates/components/submission-metadata-pages.hbs

* Add input element to PAGES metadata page
* Moved "Subjects" and "Publication" field from NIHMS to Common. 
* Without pre-populating from DOI
1.  Start a new submission. Click "next" until left handside nav bar appears
2. Go to "Metadata" section
3. Click "Next" and "Back" to see the metadata forms, including one for PAGES
Resolves #66 
Interested parties: @birkland

Added UI elements for PAGES metadata page. 

---

app/templates/components/policy-compliance-doe.hbs
app/templates/components/policy-compliance-nih.hbs
app/templates/components/policy-compliance-nsf.hbs
app/templates/components/workflow-card.hbs
app/templates/submission/show/repositories.hbs

Add spacing around some components in the submission workflow.
See #77

Issue 77 - Lay out issues with some pages in the Submission workflow

---

app/templates/login.hbs

See #80 
Login form now centered on screen.
Login template cleaned up a bit.

Issue 80 - Centering the login input boxes

---

app/templates/about.hbs

Fix typo in 'about' page

---

app/templates/components/submission-metadata-common.hbs

Resolves #88 : Change button text to "Add Author"
Resolves #86 : Button no longer clips button text, but positioning can be awkward at certain widths
At width = 600px

Modifying layout of submission metadata form

---

app/templates/application.hbs

Shows a the git commit hash in the footer area of all ember pages
2.  Create a branch from master to try it out in : `git checkout -b birkland-issue-98 master`
3.  Pull the PR into it `git pull https://github.com/birkland/pass-ember.git issue-98`
5.  Look at any page and note the commit hash at the bottom
Interested Parties: @htpvu 
Resolves #98

Add git revision hash to footer

---

app/components/workflow-group.js
app/controllers/grants/show.js
app/controllers/submission/show/compliance.js
app/controllers/submission/show/funding.js
app/controllers/submission/show/repositories.js
app/templates/grants/show.hbs
app/templates/submission/new.hbs
app/templates/submission/show/compliance.hbs
app/templates/submission/show/funding.hbs
app/templates/submission/show/index.hbs
app/templates/submission/show/repositories.hbs

* Audits all instances of `save()` in submission workflow
* Makes sure that linked objects are saved in the right order
* Makes sure that save actions return promises
* Updates/adds documentation
2.  Create a branch from master to try it out in : `git checkout -b birkland-issue-106 master`
3.  Pull the PR into it `git pull https://github.com/birkland/pass-ember.git issue-106`
* Go through various submission workflows and verify that they work as expected
(TODO:  Get a Fedora image on AWS to test this out - @esm would it be possible?  build docker images with PASS repo  https://github.com/birkland/pass-ember/ with branch …

Audit submissions to assure save-order correctness

---

app/controllers/submission/show/compliance.js

When editing submissions such existing deposits are removed (e.g. the
submission originally required deposit to NIH, but post-edits it no longer
does), the sequence of events is now:
1. Remove deposits from submission
2. Save submission
3. Clean up by deleting old deposits via `destroyRecord()`
This does not have any observable effects outside of looking at the console log
2.  Create a branch from master to try it out in : `git checkout -b birkland-issue-108 master`
3.  Pull the PR into it `git pull https://github.com/birkland/pass-ember.git issue-108`
* Open the developer tools console log in the browser and watch the …

Properly destroy deposits when removed

---

app/controllers/grants/index.js

Moved submissions count to after status in the grants Admin view

---

app/styles/app.scss
app/templates/application.hbs
app/templates/dashboard.hbs

(JIRA issue: PASS-27)
* app.scss 
* application.hbs 
* dashboard.hbs 
Updated dashboard to better match the proposed wireframe. See image for the new PASS dashboard.
* Moved JHU logo to top right
* Moved application title to top left, inside the header
* Added _grants_ and _submissions_ to navbar
* Add dashboard card for application description, currently has placeholder text
* Add dashboard card for application notifications, currently has placeholder text
* Swapped Grants and Submissions cards
* Add _Add New Submission_ button to dashboard

Update PASS dashboard according to wireframe

---

app/styles/app.scss

PASS-43
Use CSS to add an icon for columns that are sortable, but not yet sorted.

Add icon showing sortable columns in grants/submissions tables

---

app/controllers/submission/show/funding.js
app/styles/app.scss
app/templates/components/submission-funding-table.hbs
app/templates/submission/show/funding.hbs

PASS-51
Changes are visible in the New Submission workflow, when adding Awards to the submission.
* Change text `Add Grant` > `Add Award`
* Add button to rows of Awards table in the New Submission workflow. Button allows a user to remove an award from the submission.

Update the a submission workflow page: Adding awards

---

app/templates/components/submission-nav.hbs
app/templates/submission/show/attachments.hbs
app/templates/submission/show/compliance.hbs
app/templates/submission/show/metadata.hbs

PASS-64
* Awards &rarr; Awards (Optional) _nav_
* Compliance &rarr; Policies _nav + header_
* Submission Attachments &rarr; Files _nav + header_
* Submission Metadata &rarr; Metadata _header_

Changed submission navigation text and appropriate section headers

---

app/templates/components/submission-metadata-nihms.hbs

PASS-83
Sorry about the additions/deletions in git, really only a single word has been changed.

Fix typo in NIHMS metadata template

---

app/routes/application.js

PASS-84
Changed default logged in PI in test data.

Changed default logged in user name

---

app/components/workflow-basics.js
app/templates/components/workflow-basics.hbs

DOI, Title, and Journal are now required to continue through the workflow submission process.

Basics validation

---

app/components/workflow-policies.js
app/routes/application.js
app/templates/components/policy-card.hbs

Includes an ugly hack in the policy-card template that checks for JScholarship

Change description for JHU policy card

---

.travis.yml
app/components/metadata-form.js
app/components/workflow-policies.js
app/components/workflow-repositories.js
app/components/workflow-wrapper.js
app/models/journal.js
app/routes/application.js
app/templates/components/policy-card.hbs
app/templates/components/workflow-policies.hbs
app/templates/components/workflow-wrapper.hbs

If the user is using the NIH policy and is using a method A journal, they will be alerted as such with the proper text. If the user is not using a method A journal, they will be asked if they have paid the respective submission fee to their journal/publisher. If so, Pubmed Central is removed as a repository. If not, the user continues as normal.
Note:
* This does not yet hide the Pubmed Central metadata form because the metadata form is taken from the policy, not the repository. This will be added soon.
* Picking a radio button option and clicking next twice through the next two steps, then going back and changing your radio button input to the other option causes undefined behavior. This will be addressed soon.

Implement NIH checking

---

app/components/workflow-wrapper.js
app/controllers/grants/index.js
app/controllers/submissions/index.js
app/routes/submissions/index.js
app/templates/submissions/index.hbs

* Self-explanatory
* Also, makes a minor text-change to a column header, as requested by Hanh

Prevent Unfinished Submissions from Showing Up in Submissions Table

---

app/routes/application.js
app/templates/components/workflow-review.hbs

- Update embargo pages text 
- Remove embargo from review 
- Fix spelling of author

Update embargo pages text and remove embargo from review 

---

app/components/workflow-metadata.js
app/components/workflow-policies.js
app/components/workflow-repositories.js
app/models/submission.js
app/routes/submissions/new.js
app/templates/components/policy-card.hbs
app/templates/components/workflow-policies.hbs
app/templates/components/workflow-review.hbs

Fixes issues https://github.com/OA-PASS/pass-ember/issues/184, https://github.com/OA-PASS/pass-ember/issues/187, and https://github.com/OA-PASS/pass-ember/issues/189

Fix for issues #184, #187, and #189

---

app/controllers/grants/index.js
app/templates/components/pi-list-cell.hbs

This one is harder to test, we can't yet capture User data in Fedora

Resolves #177 - Remove email functionality from Corr. Author

---

app/styles/app.scss

https://github.com/OA-PASS/pass-ember/issues/200

change link color to darker blue

---

app/controllers/grants/detail.js
app/templates/grants/detail.hbs

Fixes https://github.com/OA-PASS/pass-ember/issues/225

Update wording, grant table columns, fields for #225

---

app/components/workflow-review.js

fixes: https://github.com/OA-PASS/pass-ember/issues/192

Change metadata display to author(s) and handle duplicates better

---

app/components/workflow-review.js
app/templates/components/workflow-review.hbs

https://github.com/OA-PASS/pass-ember/issues/232

Move Eric submissions in to review page and disable submit unless they have visited 

---

README.md

Small update to provide current information on using docker.
Are there other questions you would like me to address?

Update documentation on development.

---

app/routes/grants/index.js
app/templates/grants/index.hbs
yarn.lock

Fixes https://github.com/OA-PASS/pass-ember/issues/237

Load submissions in grants index every time

---

app/components/workflow-files.js
app/components/workflow-review.js
app/controllers/submissions/new.js
app/models/file.js
app/models/submission.js
app/templates/components/workflow-files.hbs
app/templates/components/workflow-review.hbs

* Switch from file POJO to file ember record
* Get submissions POSTing correctly
* Add in file role dropdown, with first file defaulting to `manuscript` and the rest defaulting to `supplement`.
* Fully regression tested

Get submissions POSTing

---

app/routes/application.js
app/templates/components/nav-bar.hbs

* Standardize capitalization of grant statuses
* Remove notifications from navbar

Minor Fixes

---

app/components/metadata-form.js
app/components/workflow-basics.js
app/components/workflow-metadata.js
app/components/workflow-review.js
app/controllers/submissions/detail.js
app/models/submission.js
app/routes/application.js
app/routes/submissions/detail.js
app/styles/app.scss
app/templates/components/nav-bar.hbs
app/templates/components/workflow-review.hbs
app/templates/grants/detail.hbs
app/templates/submissions/detail.hbs

Still need to get files working on the detail page

[WIP] Submission detail page

---

app/components/metadata-form.js
app/components/workflow-metadata.js
app/components/workflow-review.js
app/routes/application.js
app/styles/app.scss
app/templates/components/nav-bar.hbs
app/templates/components/workflow-review.hbs

- Add multiple authors 
- Fix review display of authors 
- move `select your publication type` in to drop down box.
- Manually regression tested
Fixs issues: https://github.com/OA-PASS/pass-ember/issues/219 https://github.com/OA-PASS/pass-ember/issues/182

Change metadata forms to be able to add multiple authors 

---

app/components/workflow-metadata.js
app/routes/application.js
app/styles/app.scss

Fixs: https://github.com/OA-PASS/pass-ember/issues/182

Metadata author layout inline

---

app/controllers/submissions/index.js

solves https://github.com/OA-PASS/pass-ember/issues/185

remove 'Corr. Author' for submission table 

---

app/templates/components/workflow-basics.hbs

Change title to textarea

---

app/components/metadata-form.js
app/components/workflow-basics.js
app/templates/components/workflow-basics.hbs
app/templates/components/workflow-files.hbs
app/templates/components/workflow-grants.hbs
app/templates/components/workflow-metadata.hbs
app/templates/components/workflow-policies.hbs
app/templates/components/workflow-repositories.hbs
app/templates/components/workflow-review.hbs
mirage/scenarios/test.js
package-lock.json
package.json
tests/acceptance/login-test.js
tests/acceptance/submissions/new-test.js
tests/index.html

Get partially written acceptance test for making a new submission, and the full one for logging in working.

Implement acceptance tests

---

app/components/workflow-metadata.js
app/components/workflow-repositories.js
app/styles/app.scss
app/templates/components/workflow-metadata.hbs
tests/acceptance/login-test.js

* Resolves #257 
* Fixes unticketed issue where multiple copies of JHU repo appear

Fix minor issues

---

app/components/metadata-form.js
app/components/workflow-grants.js
app/components/workflow-metadata.js
app/components/workflow-review.js
app/templates/components/workflow-review.hbs
app/templates/submissions/detail.hbs

- Update common form to use a textarea
- Filter crossref data for required fields 
- Add funder info to submission detail and review pages
- Fix grants from grant detail page not being able to be removed
- Regression tested

Filter crossref data

---

app/components/metadata-form.js
app/templates/components/workflow-metadata.hbs
tests/integration/components/metadata-form-test.js

https://github.com/OA-PASS/pass-ember/issues/282

Allow no DOI info or DOI to be present on submission

---

app/templates/index.hbs

- Due to FAQ page not being merged yet curent links on page link to about page

Update landing page text

---

app/components/metadata-form.js
app/components/workflow-metadata.js
app/routes/application.js
app/templates/components/workflow-metadata.hbs

- Move around metadata 
- Common
- JScholarship
- remove `required` from NIH 
- move ISSN to Common
- remove ISSN from NIH
- Fix metadata pre-population

Move around metadata 

---

app/controllers/grants/index.js
app/services/current-user.js

- Change grant table heading from `#` to `Submissions count`
- Fix user not being defined

Update grant table

---

app/components/workflow-basics.js

Save title and journal if no DOI is present

---

app/router.js
app/routes/faq.js
app/templates/components/nav-bar.hbs
app/templates/faq.hbs
tests/unit/routes/faq-test.js

Does most of the (relatively light) heavy lifting for https://github.com/OA-PASS/pass-ember/issues/293. Just need actual content!

Create FAQ page [WIP - needs content]

---

app/components/workflow-review.js
app/controllers/submissions/detail.js
app/templates/components/workflow-review.hbs
app/templates/submissions/detail.hbs
tests/integration/components/worflow-review-test.js

- Normalize all metadata to display capitalized keys

Normalize all metadata to display capitalized keys

---

app/controllers/grants/detail.js
app/templates/grants/detail.hbs
tests/acceptance/grants/detail-test.js
tests/acceptance/submissions/index-test.js

* Mailto link removed from PI and coPIs
* Submission table updated to be in line with updates to table in Submissions page
* Added test for grant details page

Update Grants details page

---

app/templates/submissions/detail.hbs

Add submitter info to submission detail

---

app/styles/app.scss
package-lock.json

Alternate table colors

---

app/components/workflow-grants.js
app/templates/components/workflow-basics.hbs
app/templates/components/workflow-files.hbs
app/templates/components/workflow-repositories.hbs
app/templates/components/workflow-wrapper.hbs
package-lock.json
tests/acceptance/grants/detail-test.js
tests/acceptance/grants/index-test.js
tests/acceptance/submissions/index-test.js
tests/integration/components/workflow-grants-test.js

- Renamed categories on repository
- Add text when NIHMS repo is selected to file upload page 
- Add required indicator to basic page 
- regression tested

Improve usage instructions

---

app/components/metadata-form.js
app/components/workflow-basics.js
app/components/workflow-files.js
app/controllers/application.js
app/styles/app.scss
app/templates/components/workflow-basics.hbs
app/templates/components/workflow-files.hbs
package-lock.json
package.json
tests/unit/controllers/application-test.js

- Added toasts 
- Add validation to worklflow

Add toasts, user feedback and validation 

---

app/templates/index.hbs

Add button to dashboard

---

app/templates/faq.hbs

Add FAQ text

---

app/components/workflow-metadata.js

Update text in metadata step in submission workflow

---

app/components/workflow-grants.js
app/components/workflow-metadata.js
app/components/workflow-repositories.js
app/components/workflow-review.js
app/templates/components/workflow-review.hbs

- Add External submission to metadata
- Add external submission section under repos
- Fix behavior of repos when removing and adding them

Capture external submissions in metadata

---

app/components/workflow-repositories.js
app/controllers/submissions/new.js
app/routes/submissions/new.js
app/templates/thanks.hbs

* Adds environment-checking for headers when uploading files
* Updates text on `thanks` page (#366)

Implement environment-dependent authorization for file-uploads

---

app/routes/application.js
package-lock.json
tests/acceptance-helpers.js
tests/acceptance/grants/detail-test.js
tests/acceptance/grants/index-test.js
tests/acceptance/submissions/index-test.js
tests/acceptance/submissions/new-test.js

Still don't think the root cause is necessarily fixed, but hopefully this workaround can hold

Fix failing acceptance tests

---

app/controllers/grants/detail.js
app/controllers/grants/index.js
app/controllers/submissions/index.js
app/styles/app.scss
app/templates/application.hbs
app/templates/components/nav-bar.hbs
app/templates/components/oap-compliance-cell.hbs
app/templates/components/policy-card.hbs
app/templates/components/workflow-basics.hbs
app/templates/components/workflow-files.hbs
app/templates/components/workflow-grants.hbs
app/templates/components/workflow-repositories.hbs
app/templates/contact.hbs
app/templates/grants/index.hbs
app/templates/index.hbs
app/templates/submissions/detail.hbs

Fixes the following tickets:
* #382 
* #384 
* #386 
* #387 
* #389 
* #390 
* #391 
* #392 
* #393 
* #395

Update Text (need to add screenshots)

---

app/components/workflow-review.js
app/controllers/submissions/new.js
app/templates/components/grant-submission-cell.hbs
app/templates/components/workflow-review.hbs
app/templates/components/workflow-wrapper.hbs

- Add warning to indicate to user to submit to external submission portals
- Fix grant table create new button not keeping grant when you create new submission 
- Add validation for agreeing to deposit and external submissions
- Regression tested

Better user feedback

---

app/controllers/submissions/detail.js
app/styles/app.scss
app/templates/application.hbs
app/templates/components/workflow-review.hbs
app/templates/submissions/detail.hbs

https://github.com/OA-PASS/pass-ember/issues/356
https://github.com/OA-PASS/pass-ember/issues/393
https://github.com/OA-PASS/pass-ember/issues/365

General qa

---

app/styles/app.scss
app/templates/faq.hbs
app/templates/index.hbs

Add agencies to FAQ

---

app/components/metadata-form.js

Add readonly if doi is present

---

app/controllers/submissions/new.js

https://github.com/OA-PASS/pass-ember/issues/458

remove debugger

---

.docker/shib/docker-compose.yml
app/components/workflow-repositories.js
app/routes/index.js
app/styles/app.scss
app/templates/about.hbs
app/templates/faq.hbs
app/templates/index.hbs
package-lock.json

update alerts style, Add # support to link to relevant parts of page, update compose.yml

---

app/components/workflow-repositories.js

Should resolve #456 
This PR should already have updated Docker images. 
* Navigate to `pass-ember/.docker/shib`
* You can clean old images if necessary `docker system prune -f --volumes`
* Pull latest images `docker-compose pull`
* Bring up the environment, this can take a few minutes `docker-compose up`
Once things settle, you can test in the browser:
* Navigate in a browser to `https://pass`
* Login to the `nih-user` with password `moo`
* Go to the Grants page, click `New Submission` button for a grant that has NATIONAL INSTITUTE OF HEALTH as a funder to start a new submission
* Go through the submission workflow, (optional) you can use the DOI: `10.1039/c7fo01251a`
* Depending on your answer to the user input, PubMed Central can appear in the repositories step

Did something to let PMC appear for NIH grants in repository step

---

.docker/shib/docker-compose.yml
docker-compose.yml

This should allow for more consistency across testing

Update and use hashes in Dockerfiles

---

app/templates/submissions/detail.hbs

update submission detail page if source == other

---

app/routes/grants/detail.js
app/routes/submissions/index.js
package-lock.json

Make it so up to 50 submissions can be loaded at once by frontend

---

app/components/workflow-basics.js
app/styles/app.scss
app/templates/components/workflow-review.hbs

https://github.com/OA-PASS/pass-ember/issues/466

Fix/review page repos 

---

app/templates/components/submission-status-cell.hbs

https://github.com/OA-PASS/pass-ember/issues/482

add status

---

app/templates/components/submission-status-cell.hbs

https://github.com/OA-PASS/pass-ember/issues/488

fix positon of tooltips

---

app/components/workflow-basics.js

fix bug with metadata not populating

---

app/controllers/submissions/new.js
app/templates/components/submission-action-cell.hbs

Set source to pass through workflow

---

app/components/find-grant.js
app/components/find-journal.js
app/helpers/search-associated.js
app/routes/grants/detail.js
app/routes/grants/index.js
app/routes/submissions/detail.js
app/routes/submissions/index.js
app/routes/submissions/new.js

Resolves #504 
* Bring up `pass-ember/.docker/shib` environment as normal
* Login to `incomplete-nih-user`
* Check Submissions page and see 80 total submissions
* Make sure submission details display as expected
* Goto Grants page, sort the table by _# of Submissions_, there will be two grants with large numbers of submissions (something like 78 and 69)
* Check the Grant details page for one of these grants, make sure the table shows all submissions
* Make sure you can progress through the new submission workflow as expected

Temporarily up search results max until proper paging is implemented in the UI

---

app/components/submissions-repoid-cell.js
app/styles/app.scss
app/templates/components/submission-status-cell.hbs

add more tooltips

---

app/components/submissions-repoid-cell.js
app/styles/app.scss
app/templates/components/submission-status-cell.hbs
app/templates/submissions/detail.hbs

#494 #513 #512 
* Change Manuscript ID tooltip to be the right column
* Add more tooltips for Submission status
* Fix typo in the Submission Details page

More bug fixes

---

app/components/metadata-form.js
app/components/workflow-metadata.js

hide all fields that have no data from workflow

---

app/components/workflow-grants.js

#523 
* Login to `nih-user`
* Navigate to new submission workflow (not from a grant)
* Enter basic info to get to the Grant step
* In the dropdown, select `R01EY012124 Regulation of Synaptic Plasticity in Visual Cortex`
* Click Next to show Policies step
* Policy may or may not appear

Hopefully fix policy not appearing for selected grants

---

app/components/workflow-repositories.js
app/templates/components/policy-card.hbs
app/templates/components/workflow-repositories.hbs

#537 #538 
* Login as `nih-user`
* Navigate to new submission workflow to start a new submission
* In Grants step, enter random grants
* In Policies page, **Policy cards should have sub-title that says something along the lines of: _Requires deposit into ..._**
* In Repositories step, **each repository should say _- required by &lt;some funding agency&gt;_**
* Must also verify that the end artifacts look good - so finish out the submission workflow and check the submission info - the resulting submission should have the expected Repositories listed in its details page

Adjusting text in submission workflow

---

app/components/submission-status-cell.js
app/templates/components/submission-status-cell.hbs

Update submission table status

---

app/templates/faq.hbs
app/templates/submissions/index.hbs

#566 - add description for Submissions list to top of submission page and expand on this in FAQ, remove "Your" from page heading
#563 - reformat FAQ page to make questions stand out more
Question for code review: I noticed other pages have style embedded in template, so I copied this. Is this typical for ember or should the style specific to this one template be in the `app.scss` file?

Make FAQ questions stand out, add NIH submission explanation

---

app/templates/grants/index.hbs

Update text on "Your Grants" page

---

app/templates/grants/index.hbs

Changed text at top of grants page

---

app/components/workflow-metadata.js

Change button text on JScholarship agreement message

---

app/templates/components/workflow-wrapper.hbs

https://github.com/OA-PASS/pass-ember/issues/564
Before
After

Add title to submission workflow title

---

app/routes/grants/index.js
app/routes/submissions/index.js

* Grant table sorted first by `status` then by `endDate`
* Submission table sorted first by `submittedDate`
* Submissions that don't have `submittedDate` are placed at the end

Update sorting in submission and grants table

---

app/components/submission-repo-details.js
app/templates/submissions/detail.hbs

#539 
Previously missing a requirement: https://github.com/OA-PASS/pass-ember/issues/539#issuecomment-398248550

Add 'manuscript expected' status to submission details page

---

app/components/workflow-metadata.js
app/templates/contact.hbs
app/templates/thanks.hbs

#585 - add contact for end user services
#586 (comment) - switch confirm/cancel button style on deposit agreement popup
#573 - add explanation of what to expect re: deposits to thank you page

Add contact, switch deposit agreement popup button color, add text to thank you page

---

app/templates/components/workflow-wrapper.hbs

Make sub-header in submission workflow italic

---

app/templates/components/workflow-review.hbs
app/templates/submissions/detail.hbs

https://github.com/OA-PASS/pass-ember/issues/554

Update file view layout

---

app/components/workflow-metadata.js
app/styles/app.scss

https://github.com/OA-PASS/pass-ember/issues/583

Update date time picker 

---

app/templates/contact.hbs
app/templates/faq.hbs
app/templates/thanks.hbs

#611 Add FAQ for "what to expect"
#551 Add FAQ explaining when publishers will submit to PMC
#561 Add FAQ on negotiating copyright
#585 Update contact page with End User Services address
#573 Add link to FAQ on thank you page

FAQ changes, contact page update

---

app/templates/components/carousel-gallery.hbs
app/templates/components/workflow-repositories.hbs
app/templates/index.hbs
app/templates/submissions/index.hbs

Prepend {{rootURL}} to all internal paths

---

app/styles/app.scss
app/templates/grants/detail.hbs

Fix bullet alignment on Grant details, change co-pi label

---

app/controllers/submissions/new.js
package-lock.json

This PR contains the addition of two error-catchings and makes sure that files are only saved if they're present. This PR should help users identify errors more easily, and developers debug any future problems they might find more easily. For better or for worse, I was not able to replicate any issues as they were described in ticket #588.

Strengthen file-uploading

---

app/components/workflow-basics.js
app/components/workflow-metadata.js

#637 
Call two services to grab some extra metadata. Eventually the metadata is attached to the metadata blob on the submission.
Current blob looks like the following, with the added data being: `issn-map` in the `id="common"` block and `nlmta` in the `id="pmc"` block.
If the NIH services either have no record of our ISSN(s) or otherwise return no results, current behavior is to simply not add the new fields.
``` javascript
[
{
"id":"JScholarship",
"data":{
"embargo":"NON-EXCLUSIVE LICENSE FOR USE OF MATERIALS This non-exclusive license defines the terms for the deposit of Materials in all formats into the digital repository of materials collected, preserved and made available through the Johns Hopkins Digital Repository, JScholarship. The Contributor hereby grants to Johns Hopkins a …
```

[WIP] Add pub-type and nlmta to metadata when available

---

app/templates/components/workflow-grants.hbs

2.Grants: Make contact link open in new window

---

app/components/metadata-form.js
app/components/workflow-files.js
app/controllers/grants/detail.js
app/controllers/submissions/detail.js
app/controllers/submissions/index.js
app/routes/grants/detail.js
app/routes/grants/index.js
app/routes/submissions/index.js
app/services/submission-status.js
app/templates/submissions/detail.hbs
tests/integration/components/submission-action-cell-test.js
tests/integration/components/submission-status-test.js
tests/unit/services/submission-status-test.js

#652 
This also has some random code style updates so `eslint` stops yelling at me

More submission status goodness

---

app/components/submission-repo-details.js
app/templates/components/submission-repo-details.hbs
app/templates/components/submission-status-cell.hbs
app/templates/components/submission-status.hbs
app/templates/submissions/index.hbs

* Changed tooltip text for stalled
* Changed color of button to red for stalled, fixed css so that this color change works
* Moved the `<style>` tags to the top of the Submissions page as they were being repeated for every cell (that means any page that puts the status cell on will need those style tags, is this OK? Alternatively could move it to main stylesheet)

Edited submission status tooltip text, fixed CSS for Stalled

---

app/index.html
tests/index.html

Corresponding PR for pass-ui-static must be merged as well, as static ui currently depends on this title to check if someone is logged in:
https://github.com/OA-PASS/pass-ui-static/pull/7

Change page title to "PASS"

---

app/components/submission-repo-details.js
app/services/submission-status.js
app/templates/components/submission-repo-details.hbs
app/templates/components/submission-status-cell.hbs
app/templates/components/submission-status.hbs

Just want to throw something up for people to test

Try messing with submission status a bit

---

app/initializers/application.js
app/routes/grants/detail.js
app/routes/submissions/detail.js

* Bad object IDs in the URL should 404 now
* User not allowed in the system are booted to the static 401 error page
Can test 401 with user `staff2`

Slightly improved error handling

---

app/components/metadata-form.js
app/components/workflow-metadata.js
app/styles/app.scss
package-lock.json

https://github.com/OA-PASS/pass-ember/issues/660
- For the action buttons for authors. the solution is to just display it always
- Can not change the text of `add new item`
- Removed values not unique text
- Remove italics
- fix spacing
- allow adding of authors when NO DOI is present

Metadata form: Author field display issues 

---

app/components/metadata-form.js
app/components/workflow-metadata.js
app/styles/app.scss
package-lock.json

https://github.com/OA-PASS/pass-ember/issues/692
Cause:
What was happening is some DOI have a subtitle which was getting assigned to the title prop of the metadata. thus causing the title prop to be undefined on the metadata object.
Solution:
Add a check for subtitle and if its there don't let it assign to the title prop.

Investigate a code path where no title provided

---

app/components/metadata-form.js
app/components/workflow-metadata.js
app/components/workflow-review.js
app/styles/app.scss
app/templates/components/workflow-basics.hbs
app/templates/components/workflow-files.hbs
app/templates/components/workflow-grants.hbs
app/templates/components/workflow-policies.hbs
app/templates/components/workflow-repositories.hbs
app/templates/components/workflow-wrapper.hbs
package-lock.json

https://github.com/OA-PASS/pass-ember/issues/666

Add overlay when submitting to prevent user from clicking

---

package-lock.json
package.json

* Grab this update
* Run `npm install`
* Check for vulnerabilities `npm audit`

Update dependencies to address vulnerabilities

---

app/routes/check-session-route.js
app/routes/grants/detail.js
app/routes/submissions/detail.js
app/services/error-handler.js

A supplement to PR #706, which produced some unpredictable behavior during testing. The following changes were made:
* Changed session timeout checker to run on `beforeModel()` to avoid problems with model code attempting to run after timeout.
* Modified two `details.js` pages to ensure parent beforeModel() runs first
* Modified two `details.js` pages to get rid of confusing 404 errors that may be triggered in situations that are not necessarily 404s. There were 4 of these, two now use a new error handler for failing to load data (this usually occurs due to session timeout or some kind of dropped connection and so prompts a page reload). The other two were removed so that default error handling takes care of these.
This is primarily related to #345, but also fixes the cause of #678.
We …

Additional session timeout fixes

---

.docker/shib/docker-compose.yml
app/components/metadata-form.js
app/components/workflow-metadata.js
app/instance-initializers/error-handler.js
app/services/error-handler.js
app/services/metadata-blob.js
app/styles/app.scss
package-lock.json

https://github.com/OA-PASS/pass-ember/issues/736
```JSON
{
"id":"JScholarship",
"schema":{
"title":"Deposit Details - JScholarship <br><p class='lead text-muted'>Please provide the information and agreement required for JScholarship deposit.</p> <p class='lead text-muted'> <i class='glyphicon glyphicon-info-sign'></i> Fields that are not editable were populated using information associated with the provided DOI or were provided in a previous step. To edit authors list, please go back to “Publication Details” page via the “Back” button below.</p>",
"type":"object",
"properties":{
"authors":{
"title":"<div class=\"row\"><div class=\"col-6\">Author(s) <small class=\"text-muted\">(required)</small></div><div class=\"col-6 p-0\"></div></div>",
"type":"array",
"uniqueItems":true,
"items":{ …
```

Add optional fields back and add authors to jscholership

---

app/components/workflow-metadata.js
package-lock.json

Also fix duplicate crossref, pmc, and agent_information showing up

Fix metadata common not being updated. 

---

app/templates/faq.hbs

Access is now broader than previously.
Closes #754

Update FAQ for who can access PASS

---

app/components/workflow-review.js
app/controllers/submissions/new.js
app/templates/components/workflow-wrapper.hbs
app/templates/submissions/new.hbs

Remove unused and conflicting userIsPreparer function

---

app/controllers/submissions/detail.js
app/controllers/submissions/new.js

Only populate submittedDate when submitted is being set to true

---

.docker/shib/docker-compose.yml
app/components/submission-repo-details.js
app/components/workflow-metadata.js
app/components/workflow-review.js
app/controllers/submissions/detail.js
app/controllers/submissions/new.js
app/templates/components/submission-repo-details.hbs
app/templates/submissions/detail.hbs

Changes:
- Fixes some string literal lint issues
- Use Repository.integrationType to find weblink repos
- Updates to assets image with Repository.integrationType
- Removes or comments out various debugger statements
- When creating a proxy submission
- Do not remove weblink repositories from Submission 
- Do not add external-submissions metadata to Submission
- Are not required to click for weblink repositories
- Submissions details page of new submission
- Repositories section includes ERIC
- No link to ERIC provided
- No "external submission repositories" section
- When approving a proxy submission
- Remove weblink repositories from Submission
- Add external-submissions metadata to Submission
- Are required to click for weblink repositories
- Submissions details page before approval
- …

Fix handling of weblink repositories

---

app/components/workflow-basics.js
app/templates/components/workflow-basics.hbs

Adds email validation to the Basics form. Removes unused "emailLookup".
Closes #799

Add email validation to Basics form

---

app/templates/thanks.hbs

Generalize thank you page text to allow for proxy submitter use case

---

app/templates/about.hbs

Update about text 
closes #826

Update about text

---

app/components/grant-link-newtab-cell.js
app/components/grant-title-date-cell.js
app/components/select-row-toggle.js
app/components/workflow-grants.js
app/controllers/grants/index.js
app/controllers/submissions/index.js
app/styles/app.scss
app/templates/components/grant-link-newtab-cell.hbs
app/templates/components/grant-title-date-cell.hbs
app/templates/components/submission-funding-table.hbs
app/templates/components/workflow-grants.hbs

One of the changes may have an impact on the column widths on the /grants/ and /submissions/ tables, so these should be checked as well.
For details see issue #830

Make minor changes to new grants tab layout

---

app/components/workflow-metadata.js
app/components/workflow-review.js
app/controllers/submissions/detail.js
app/services/current-user.js
app/services/error-handler.js
tests/integration/components/workflow-review-test.js
tests/unit/controllers/submissions/new/review-test.js

The user no longer agrees to repository policies in the metadata step. Instead the user agrees in the final workflow review step.
Closes  https://github.com/OA-PASS/pass-ember/issues/874

Move repository agreement to review step of workflow

---

.docker/shib/docker-compose.yml

Contains alpaca ordering and label tweaks

Use schema service v0.1.1

---

package-lock.json
package.json

Update ember-fedora-adapter dependency version

---

app/components/workflow-basics.js
app/services/doi.js
config/environment.js

Sample DOI that has a lot of data: `10.1039/c7an01256j`
Closes #869

Use Crossref API to get data related to a DOI instead of using the DOI resolver

---

app/services/current-user.js
tests/unit/services/current-user-test.js

Refactors current-user service to be more understandable and adds tests.
Closes #902

Refactor current-user service

---

app/components/metadata-form.js

Get rid of the document.onready thing with call to alpaca

---

.docker/docker-compose.yml

Update schema service image

---

app/components/workflow-basics.js

Closes #957 
Replaces a previous PR with the same change, this time with slightly cleaner implementation.

Overwrite Publication with DOI data if it's missing info

---

app/templates/components/workflow-grants.hbs
app/templates/grants/index.hbs

Update grant text

---

app/components/found-manuscripts/component.js
app/components/found-manuscripts/template.hbs

- better handle file download errors
- fix loading spinner

UI tweaks to download manuscripts

---

config/deprecation-workflow.js
mirage/config.js
package.json
yarn.lock

- we were experiencing a lot of deprecation warnings
- this addon will silence the warnings until we have time to address them

adds ember deprecation workflow addon

---

.gitignore
README.md
app/adapters/application.js
app/controllers/submissions/detail.js
app/index.html
app/routes/dashboard.js
app/serializers/application.js
app/services/app-static-config.js
app/services/autocomplete.js
app/services/current-user.js
app/services/doi.js
app/services/error-handler.js
app/services/metadata-schema.js
app/services/oa-manuscript-service.js
app/services/policies.js
app/services/submission-handler.js
config/environment.js
ember-cli-build.js
mirage/config.js
package.json
tests/index.html
tests/unit/instance-initializers/error-handler-test.js
yarn.lock

- move to new passs-ember-adapter package v0.1.0
- ignore python config

Prep for v0.1.0 release

---

app/services/current-user.js
config/environment.js
mirage/config.js
mirage/custom-fixtures/nih-submission/doi-journals.js
mirage/fixtures/repositories.js
tests/integration/components/workflow-files-test.js
tests/unit/routes/submissions/index-test.js
tests/unit/services/current-user-test.js
tests/unit/services/policies-test.js

* Setup passthrough for data requests
* Mock other services with Mirage

Updating json api stuff

---

README.md
app/adapters/application.js
app/services/doi.js
app/services/policies.js
config/environment.js

* Should probably disable Mirage by default

Read adapter host and namespace from env vars

---

mirage/config.js

Necessary for demo env in pass-docker

Pass through pass.local in mirage

---

mirage/config.js

Update `schema.<model>.fn` calls to `schema.fn('model')`

Update Mirage schema calls

---

mirage/config.js

* Also turns on Mirage logging (redundant?)

Add various passthroughs to Mirage

---

app/routes/grants/detail.js

* Add a check to the submission query on grant details page to not show any incomplete submissions from other users

Add demo users

---

.github/workflows/release.yml

Should fix the errors we encountered during last release

Add git config to workflow

---

app/components/found-manuscripts/index.hbs
app/components/select-row-toggle/index.hbs
app/components/workflow-files/index.hbs
app/components/workflow-files/index.js
app/controllers/submissions/new/files.js
app/helpers/search-associated.js
app/index.html
app/models/file.js
app/routes/submissions/detail.js
app/routes/submissions/new.js
app/services/doi.js
app/services/metadata-schema.js
app/services/oa-manuscript-service.js
app/services/policies.js
app/services/search-helper.js
app/services/submission-handler.js
config/environment.js
mirage/config.js
package.json
tests/acceptance/nih-submission-test.js
tests/index.html
tests/integration/components/workflow-files-test.js
tests/integration/components/workflow-grants-test.js
tests/unit/controllers/submissions/new/files-test.js

Addresses: https://github.com/eclipse-pass/main/issues/459

File service integration

---

.github/actions/build-pass-ui/action.yml
.github/workflows/update-docker-image.yml
build.sh
package.json

Update automation to push docker tags for `ghcr.io/eclipse-pass/pass-ui`:
* `:latest`
* `:$project-version`

Update automation to publish project version tag

---

app/services/metadata-schema.js
config/environment.js
mirage/config.js
mirage/routes/schemas.js
tests/integration/components/workflow-metadata-test.js
tests/unit/services/metadata-schema-test.js

Seems to work to make requests, but the service in pass-core is not ready yet

Remove schema service mocking, update service URL path

---

app/components/repository-card/index.hbs
app/controllers/submissions/detail.js
app/services/policies.js
config/environment.js
mirage/config.js
tests/acceptance/nih-submission-test.js
tests/integration/components/choice-repositories-card-test.js
tests/unit/services/policies-test.js

Remove mocking for policy service

Policy service

---

app/components/submission-funding-table/index.hbs
app/components/workflow-grants/index.hbs
app/components/workflow-grants/index.js
app/controllers/submissions/new/basics.js
app/controllers/submissions/new/grants.js
app/routes/submissions/new.js
tests/integration/components/workflow-grants-test.js

- alias being a computed was kicking off a re-computation during the render cycle
- this was causing a rendering bug
- this sets the model value as the expected variable name in the setupController method
- we should remove all aliases in the future
Closes: https://github.com/eclipse-pass/main/issues/696

fix: grant preload bug

---

app/components/metadata-form/index.js

Closes: https://github.com/eclipse-pass/main/issues/709

fix: reorder metadata step action buttons to align with rest of workflow

---

app/components/notice-banner/index.hbs
app/components/policy-card/index.hbs
app/components/workflow-grants/index.hbs
app/components/workflow-metadata/index.hbs
app/components/workflow-repositories/index.hbs
app/components/workflow-review/index.hbs
app/components/workflow-wrapper/index.hbs
app/templates/application.hbs
public/branding-overrides.css
tests/integration/components/workflow-metadata-test.js

Closes: https://github.com/eclipse-pass/main/issues/745

Accessibility best practices

---

app/controllers/grants/index.js
tests/acceptance/nih-submission-test.js
tests/integration/helpers/format-oap-compliance-test.js

per discussions on slack we're removing this column until we can better determine what policy compliance means

fix: remove compliance column in grants index table

---

app/components/workflow-basics/index.hbs
app/components/workflow-basics/index.js
app/controllers/submissions/new/basics.js
app/templates/submissions/new/basics.hbs
tests/integration/components/workflow-basics-test.js
tests/unit/controllers/submissions/new/basics-test.js

Closes: https://github.com/eclipse-pass/main/issues/791

fix: prevent double click on workflow basics next btn

---

.github/workflows/ci.yml

Duplicates some setup in order to run tests / acceptance tests in parallel

Try running acceptance tests in parallel with regular tests

---

.github/workflows/ci.yml
.github/workflows/update-docker-image.yml

Needed for complete workflow PR: https://github.com/eclipse-pass/main/pull/980

Ignore pushes to main with tags in workflows

---

app/components/nav-bar/index.js
app/services/session.js

This PR changes logout to POST to `/logout` when logout is clicked.
This PR goes with this `pass-core` PR, both need to merged at the same time.

Enable CSRF for logout

---

app/components/submission-repo-details/index.js
app/styles/app.css
tests/integration/components/submission-repo-details-test.js

Needed for this PR: https://github.com/eclipse-pass/pass-support/pull/148

Add deposit status retry support

---

ember-cli-build.js

`ember-modal-dialog` CSS was not being included in build.

Fix modal layout bug
