app/components/find-journal.js
app/components/submission-overview-details.js
app/templates/components/find-journal.hbs
app/templates/components/submission-overview-details.hbs
app/templates/components/submission-overview-view.hbs
tests/integration/components/find-journal-test.js

* Adds a widget for selecting a journal
* Automatically selects the journal if detected from the DOI
2.  Create a branch from master to try it out in : `git checkout -b birkland-issue-18 master`
3.  Pull the PR into it `git pull https://github.com/birkland/pass-ember.git issue-18`
* Without pre-populating from DOI
1.  Start a new submission.  Do not enter a DOI.  Click next
2. Enter in an arbitrary title.  Start typing in the journal search box and select a journal
3. Click 'save and continue', you should still see the journal in the summary
* With pre-populating a DOI
1. Start a new submission.  Enter in a viable DOI that …

Add journal search to overview

---

app/components/submission-metadata-common.js
app/components/submission-metadata-nihms.js
app/components/submission-metadata-pages.js
app/components/submission-metadata-par.js
app/components/workflow-group.js
app/templates/components/submission-metadata-common.hbs
app/templates/components/submission-metadata-nihms.hbs
app/templates/components/submission-metadata-pages.hbs
app/templates/components/submission-metadata-par.hbs
app/templates/components/workflow-card.hbs
app/templates/submission/show/metadata.hbs
tests/integration/components/submission-metadata-common-test.js
tests/integration/components/submission-metadata-nihms-test.js
tests/integration/components/submission-metadata-pages-test.js
tests/integration/components/submission-metadata-par-test.js

* Adds content to the "metadata" submission step
* Adds components for each type of metadata (common, nihms, pages, par)
* Adds a 'back' button option, uses it to page back and forth through the metadata
* HTML for each individual metadata step can be found in `templates/components/submission-metadata-{name}.hbs`.  Each one has some default/example forms
2.  Create a branch from master to try it out in : `git checkout -b birkland-issue-49 master`
3.  Pull the PR into it `git pull https://github.com/birkland/pass-ember.git issue-49`
* Create a new submission. 
1. Feel free to click past the DOI and journal/title pages and …

Add metadata skeleton

---

app/templates/grants/show.hbs
app/templates/submission/new.hbs
app/templates/submission/show/funding.hbs
app/templates/submission/show/index.hbs

* Transitions directly to next submission step upon `Save and Continue`, instead of the 'review' card
* Adds a 'back' button where appropriate to overview and funding steps
* This pattern will be carried forward as 'compliance' and 'metadata', etc go live
2.  Create a branch from master to try it out in : `git checkout -b birkland-issue-47 master`
3.  Pull the PR into it `git pull https://github.com/birkland/pass-ember.git issue-47`
* Create a new submission via the grants table
* After clicking 'next' on the DOI stage, you now see a 'back' button that will allow you to go back to DOI entry
* Note:  the DOI auto-population …

Submission navigation updates

---

app/templates/submission/show/attachments.hbs

* Added input elements to "Attachments" page
* Added back/next navigation buttons to the "Attachments" page
* Without pre-populating from DOI
1.  Start a new submission. Click "next" until left handside nav bar appears
2. Go to "Attachments" section
3. Click "Next" and "Back" to advance/go back in the workflow
Resolves #69
Interested parties: @birkland

Added UI element to attachment page template

---

app/index.html

The Bootstrap documentation is not clear about this, but the 'file upload' form example relies on the HTML doc language to be set. Sets default doc lang to "en"
Resolves #71

Issue 71 - Make file upload forms look nice

---

app/templates/components/workflow-card.hbs

Submission workflow buttons re-organized. New buttons are placed at the bottom, as before, but the button toolbar no longer takes up the full width of the component. Any buttons that would overflow the component now break onto a new line. 
These changes apply to buttons:
* View Submissions > Create new Submission workflow
* View Submissions > click an award number > New Submission modal that pops up
* Submission details > Overview, Awards, Metadata, Attachments sections
Examples of new button behavior shown below:

Issue 62 - Layout issue on the submission's journal selection modal pop up 

---

app/components/workflow-group.js
app/controllers/submission/show/metadata.js
app/helpers/workflow-for.js
app/templates/submission/show/metadata.hbs
tests/unit/controllers/submission/show/metadata-test.js

* Shows _only_ those metadata forms required by the current selection of deposit repositories.  If that list changes, the selection of metadata forms will change.
* Navigation buttons will navigate between metadata forms, or transition to a different submission step (in the case of back on the first MD form, next on the last MD form),
2.  Create a branch from master to try it out in : `git checkout -b birkland-issue-79 master`
3.  Pull the PR into it `git pull https://github.com/birkland/pass-ember.git issue-79`
* Do things that change the repository list, and verify that the metadata is pertinent.  There are too many ways …

Filter out unneeded metadata forms based on deposits

---

app/helpers/repo-name.js
app/templates/submission/show/repositories.hbs

Resolves issue #96, changing text in the new submission workflow section where a user selects repositories. A Handlebars helper was added and used to translate the repository acronyms used in the demo data to the desired text.
Go through the new submission workflow:
* From home page, click Submissions > Create new Submission (button) OR from either _Grants_ or _Submissions_ pages, click any award number > New Submission (button)
* _Next > Save and Continue_ Click through until you get to Submission Details page. Add awards here if you want.
* _Save and Continue_ to get to Compliance section. If awards were added to this submission, any relevant compliance statements will appear here.
* _Save and Continue_ to get to Repositories section. Text changes are seen here. For each compliance …

Issue 96 : UI text changes

---

app/adapters/application.js
config/environment.js

Currently, the ember app looks for an environment variable `PASS_FEDORA_HOST`.
If this is not given, then inspect `window.location` for host, protocol, and port.
This is useful in situations where the specific identity Fedora host is not known
ahead of time, but is known to be on the same host as ember
/cc @htpvu

Inspect window.location for api host if none given

---

.travis.yml

* Adds recommended [workaround](https://github.com/travis-ci/travis-ci/issues/8836#issuecomment-356362524) for Chrome failures due to meltdown patches at travis-CI
* Look for the green "build passed" icon when Travis builds.

Add workaround for Travis failures.

---

app/components/remaining-repos.js
app/helpers/repo-name.js

* Adds a "JHU Data Archive" option when selecting repositories
2.  Create a branch from master to try it out in : `git checkout -b birkland-jhu-archive master`
3.  Pull the PR into it `git pull https://github.com/birkland/pass-ember.git jhu-archive`
* Go through the submission workflow until you see "repositories" step.  Verify that "JHU Data Archive is present, and that it can be added to the list of repositories to deposit to"
Interested Parties: @htpvu

Add JHU data archive as a repo

---

app/controllers/application.js

Closes issue #44 
Added rootURL environment variable as extension to default Controller so that it could be used to form the logo path on any page. Previously the logo was only working on paths with one subfolder because `src="logo.png"` was sufficient to find the image in the root directory. Navigating to sub-folders as in `/grants/1` was causing the relative path to fail (../logo.png would have been required).

Make rootURL available to all pages

---

app/helpers/optional-link.js
app/routes/application.js
app/templates/components/identifier-cell.hbs
app/templates/components/submissions-repoid-cell.hbs
tests/integration/components/identifier-cell-nolink-test.js

Closes #115
Closes #102 (now easily resolved using changes for 115)
- adds helper method "optional-link" that uses a uri and label param to determine whether an `<a href...` tag should be displayed. If a URI has not been defined or the field is there but empty, the identifier will show as plain text with no link. If a URI is present, it will convert the identifier to a link
- applies this helper to the "COEUS" and "Repo ID" columns so that empty URIs aren't hyperlinked
- removes fake COEUS URIs from data since no longer used
- adds tests to exercise the variations for the new helper 
_Note: code does not confirm whether it is a URL rather than just a URI._

Adds optional-link helper and removes fake COEUS URIs

---

app/templates/grants/index.hbs
app/templates/submissions.hbs

See JIRA issue PASS-28
We still have a global filter box above the grants/submissions table, however, the filter boxes that had appeared above certain columns no longer appear.

Disable per-column filtering

---

app/styles/app.scss

PASS-41
Here is a CSS hack that addresses the size discrepancy between the search box and the _clear_ button.

Resize search box in grants/submissions tables

---

app/templates/components/pi-list-cell.hbs
app/templates/components/submissions-author-cell.hbs

PASS-42
"Contact author/PI" components in the Grants and Submissions tables 
* Now look like normal hyperlinks
* Added on-hover tooltip

Change look of 'contact author/pi' links in grants/submissions tables

---

app/controllers/submission/show/repositories.js
app/templates/submission/show/repositories.hbs

PASS-66
* Header and explanation text changes
* List of displayed repositories no longer allows users to arbitrarily add other repositories
* List of displayed repos no longer displays JScholarship
* JScholarship now shows under a 'Local' repositories section with a checkbox
- Checkbox is checked by default
* New deposit is created to JScholarship when the user clicks _Save and Continue_ only when necessary
@htpvu

Modify submission workflow "repositories" step

---

app/components/policy-compliance-nih.js
app/controllers/submission/show/compliance.js
app/controllers/submission/show/repositories.js
app/templates/submission/show/repositories.hbs

* Sometimes necessary repositories are not populated in the list. Say a submission has one NIH award that will require a deposit to PubMed. In this case, PubMed may not appear in the Repositories list.
* If a submission already has deposits to any repository, they _should_ appear in the Repositories list anyway. If no deposit has yet been created for this award in the submission, it will not appear in the Repo list in its current state.
* If a user goes directly to the Repositories step for any submission that does not have deposits created in the DB, nothing will appear. In this case of direct navigation, only previously created deposits are shown. A user must go through the workflow from at least Policies step, then click Save and Continue in order for PASS to create new deposits.
* A …

Submission workflow Repositories list population issue

---

app/components/policy-card.js
app/components/workflow-policies.js
app/components/workflow-repositories.js
app/templates/components/policy-card.hbs
app/templates/components/workflow-policies.hbs

To reiterate behavior for NIH grants:
* Method A journals, text is displayed to user saying they do not need to submit to PMC, PMC is removed from the submission repositories list
* Other journals, text is displayed to user saying they can submit to PMC through PASS or make arrangements with journal/publisher
* If external arrangements are made, remove PMC from submission repositories list
* else continue with workflow with PMC in the submission repositories list
Sample DOIs to use in the workflow:
* no pmc (Journal is not NIH related, does not have pmcParticipation): 10.1103/PhysRevFluids.1.073604
* method A: 10.1021/acsmedchemlett.7b00397
* method B: 10.1039/c7fo01251a

NIH related radios moved into NIH policy card

---

app/components/metadata-form.js
app/components/workflow-metadata.js
app/components/workflow-repositories.js
app/routes/application.js

* Fix bug where going back and forth between metadata and repositories steps breaks metadata
* Metadata now properly shows up in the review step (and saves to the submission model)
* Laid the groundwork for being able to go back and edit which repositories you want to submit to (i.e. metadata forms will properly update when a link to a repository is deleted)
* Going back a step and attempting to remove repositories after you've selected them will not actually remove them. This is being worked on this evening!

Metadata fix

---

app/components/workflow-files.js
app/templates/components/workflow-files.hbs

`Next` button is disabled if no files are present.
Fixes https://github.com/OA-PASS/pass-ember/issues/191.

Enable file validation

---

.elasticsearch.yml
.env
.travis.yml
.wait.sh
app/adapters/application.js
app/serializers/application.js
config/environment.js
docker-compose.yml
package-lock.json

Adds Elasticsearch and pass-indexer containers to docker. Objects added to Fedora will be automatically indexed. See https://github.com/OA-PASS/pass-indexer for more info.
Update to latest ember-fedora-adapter with support for search. 
To test, docker-compose up, wait for the indexer to find both Fedora and elastic search, and then run the app. There will be some errors due to the Ember model not matching the current pass context when test data is created.

Update docker to include search support

---

app/routes/submissions/new.js

Issue #238 and another unrelated bug
This bug would trigger after a user would start a new submission from the Grants Details page. This would seed the new submission with the specific grant, as expected. If a user would then leave the submission workflow, either finishing the submission or navigating to a different route, then create a new submission from anywhere. In this case, the grant from the first submission would automatically be added to this second new submission. The user would be unable to remove this grant in any way.
So this seems to be caused by Embers particular way of handling query parameters in routes. By default, Ember will make these parameters 'sticky' such that if you were to navigate away from a route then come back to the route, the query parameter would be added …

Fix sticky grants on submission and incomplete submissions being displayed

---

app/components/submission-nav.js
app/components/workflow-wrapper.js
app/templates/components/submission-nav.hbs
app/templates/components/workflow-files.hbs
app/templates/components/workflow-wrapper.hbs

Prevents people from skipping ahead farther than they've clicked `next` buttons for. Adds `disabled` attribute to links in submission nav that have not been reached yet in the workflow. Fixes https://github.com/OA-PASS/pass-ember/issues/254.

Add progress-checking to submission nav

---

.gitignore
.travis.yml
config/coverage.js
package-lock.json
package.json

This PR should add test coverage monitoring to Travis builds. 
Feedback is appreciated, since I've never messed with Travis or Coveralls before! I'm especially not sure if there is a better way to send coverage results to Coveralls in the Travis config. Right now it does some stuff along side the tests:
`npm test && echo "Reporting coveralls" && cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage`
* Let's see if this thing works - testing on my fork seemed to work
* `ember-cli-code-coverage` and `coveralls` is added to the project.
* Coverage can be triggered by setting environment variable `COVERAGE=true`
* You can get the test coverage locally if you want: `COVERAGE=true npm test` which will create a `./coverage` directory with the results.
* You can't …

Adding Coveralls

---

app/components/submission-status-cell.js
app/controllers/submissions/index.js
app/index.html
app/models/submission.js
app/routes/submissions/index.js
app/templates/components/grant-link-cell.hbs
app/templates/components/submission-status-cell.hbs
app/templates/components/submissions-article-cell.hbs
app/templates/components/submissions-award-cell.hbs
app/templates/components/submissions-repo-cell.hbs
app/templates/components/submissions-repoid-cell.hbs
app/templates/submissions/index.hbs
tests/integration/components/submission-status-cell-test.js
tests/unit/controllers/dashboard-test.js

#Notes
Award, repository, and title columns are now searchable and sortable. This was done by adding computed fields to submissions - arrays of strings - containing the text for each of those categories, and setting the relevant column's `propertyName` to that property.

Add sorting and filtering back into ember-models-table for submissions

---

app/controllers/grants/detail.js
app/controllers/submissions/index.js
app/templates/components/submissions-repo-cell.hbs

- Switch names on submission table
- Standardize repo to repository column name

Rename "OAP Repo id" field on Submissions table to "Ext. Repo Id"

---

app/models/policy.js

This relationship was adding bad Policy objects to Fedora. Looks like it was leftover from an earlier version of the Ember model.

Remove policy.funder relationship from Ember Policy model

---

.travis.yml
app/controllers/grants/index.js
app/controllers/submissions/index.js
app/models/user.js
app/routes/application.js
app/routes/grants/index.js
app/routes/submissions/index.js
app/templates/components/pi-list-cell.hbs
app/templates/components/submissions-article-cell.hbs
app/templates/components/submissions-repo-cell.hbs
app/templates/grants/index.hbs
app/templates/submissions/index.hbs
mirage/config.js
mirage/scenarios/test.js
tests/acceptance-helpers.js
tests/acceptance/grants/index-test.js
tests/acceptance/submissions/index-test.js

Work in progress PR to update various views to show only content relevant to the currently logged in user.
- ~~Grant-picker in the submission workflow should contain only grants where the current user is the PI #322~~ Will be rolled into separate PR
Will include an efficiency pass for using the search service (#280)

Show only content relevant to logged in user in the Grants and Submissions tables

---

README.md
config/environment.js
docker-compose.yml

For production deployment, the ember fedora adapter should not add an Authorization header to requests.
This pr allows the FEDORA_ADAPTER_USER and FEDORA_ADAPTER_PASSWORD environment variables to be set to empty strings in order to disable the Authorization header. 
The fcrepo version also gets bumped.

Allow Authorization head to be removed from ember fedora adapter requests

---

.docker/shib/.env
.docker/shib/docker-compose.yml
.env
config/environment.js
docker-compose.yml

This line may require an update at some point, but not sure what to: https://github.com/OA-PASS/pass-ember/blob/55f43dcd3a400e2548f2cf922d89fcca29c80b2b/app/components/workflow-files.js#L53

Replace example.org in context URL with oapass.org

---

.docker/shib/.env
.docker/shib/docker-compose.yml
.docker/shib/package-lock.json

This updates the shib configuration so the user service and real data should be available.
To test `docker-compose up`, wait a while for things to settle, login as staff1:moo and check that you can see grants.

Fixup shib

---

app/components/find-journal.js
app/components/workflow-basics.js
app/models/journal.js
app/templates/components/find-journal.hbs

This PR steps back from using autocomplete temporarily in order to work around some incomplete Journal data. `Store.query` is now used, which results in less user friendly behavior in the journal picker widget. This behavior should be OK for initial testing.
Testing should be done in the new docker shib environment in this repository. 
* Navigate to `pass-ember/.docker/shib`
* (Optional) make sure images and volumes are cleaned out with `docker-compose down -v` or if you want to be extra paranoid: `docker-compose down && docker system prune -f && docker volume prune -f`
* Make sure you have up-to-date images: `docker-compose pull`
* Run `docker-compose up` to bring the environment up.
* When things settle, you can navigate to `https://pass` in your browser to bring up PASS.
* Use known …

User Store.query for journal picker, get it working with incomplete data

---

.docker/shib/docker-compose.yml

Adds new test users with appropriate grants:
* `nih-user`
* `ed-user`
* `usaid-user`
Remember to bring down the environment and pull new images. Only `fcrepo` and `ldap` images are updated
Verified locally

Bump shib env image versions to add new test users

---

.docker/shib/docker-compose.yml

By default, Apache (`proxy` and `sp` images) would automatically return a 404 for any URL that had an encoded slash.  This was problematic when hitting the browser's reload button, for example.   This PR updates the images so that these URLs are passed on unmolested.

Fix 404 error when reloading ember URLs through shib

---

app/routes/submissions/detail.js
app/templates/components/submissions-repoid-cell.hbs
app/templates/submissions/detail.hbs

Resolves #471 
Resolves #489 
* Do the normal Docker setup
* Login as `nih-user`
* Navigate to Submissions page to see table of all submissions for this user
* **One submission should show data in the Manuscript ID column**
* Click on the article title of that submission to see its details page
* **There should be a Manuscript ID row with a clickable link to the manuscript**

Add manuscript IDs to submission details page

---

app/styles/app.scss
app/templates/components/submissions-repoid-cell.hbs
app/templates/submissions/detail.hbs

Resolves #498 
* Bring up `pass-ember/.docker/shib` env as normal
* Login to `nih-user`
* Navigate to Submissions page
* **One submission should have no _Manuscript ID_ data, message should say as much**
* Navigate to that submission's details page
* **Manuscript ID field should have message saying none found or whatever**

Add message for Manuscript ID fields when none is found

---

app/routes/grants/index.js

#497 
* Start up dev environment as normal
* _Note that this requires the updated `ember-fedora-adapter`, so if you have not recently rebuilt your `ember` container, you must do so in order for this dependency to be picked up_
* Login to `nih-user`
* Navigate to Grants page
* **The two _active_ grants should be at the top of the table, followed by the rest of the grants - all _terminated_**. Table sort behaves like before

Grants table sorts by awardStatus by default

---

app/controllers/submissions/index.js
app/styles/app.scss
app/templates/components/submissions-repoid-cell.hbs
app/templates/submissions/detail.hbs

* Force multiple externalIds onto separate lines
* Change submissions table col widths
* Change submissions table 'Manuscript ID' -> 'Manuscript IDs'
* Remove Last Update column
#507 
* Setup Docker env as normal
* Login to `incomplete nih-user`
* Navigate to Submissions table
* **Check widths of columns to make sure things look OK**
* **Make sure Last Update Date column is gone**
* **Some submissions will have 2 Manuscript IDs, make sure they display on different lines**
* **Check this behavior in the Submission details as well**

Changing submissions table/details text and style

---

package-lock.json
package.json

The deployed files created by `ember build --production` throw an error
about missing lodash.  This is an attempt to fix that by doing an `ember install ember-lodash`, and committing the updated dependencies.
I tested a static build via `ember build --production`, with files served up by nginx.  The error went away when built using this PR
* Make sure this did not break anything unintended.
* `npm` (or whatever package manager is used underneath) was unkind to `package-lock.json`, and re-arranged many lines it didn't need to.  This makes it difficult to reason about what `ember install ember-lodash` did.

Install ember-lodash to fix dependency problem

---

app/components/workflow-grants.js

#530 
Also fixes an undocumented bug where creating a submission directly from a grant did not pre-populate the submission with the grant in Firefox
Follow steps detailed in the related ticket, behavior should be verified in Firefox and Chrome, and whatever other browsers

Fix bug in Grants step that happens in Firefox

---

app/controllers/grants/index.js
app/controllers/submissions/index.js
app/templates/submissions/index.hbs

#518 
Grants and Submissions table pages have been changed to show 50 entries by default. Possible options now 10, 25, 50.

Change default table page size to 50

---

app/templates/components/workflow-repositories.hbs

#537
* Checkbox is now completely removed if JScholarship is the only repository shown in the Repositories step

Get Repositories step to show which funders require the shown repositories

---

app/styles/app.scss

#516 
Note that this font and the previous font are both compliant with JHU branding guidelines, which doesn't have much to say about font sizes. http://brand.jhu.edu/typography/

Revert font back to gentona-light

---

app/components/workflow-basics.js
app/routes/submissions/new.js
app/services/autocomplete.js

#521 
* Autocomplete now shows up to 100 suggestions as user types in the journal picker.
* When valid DOI is input, the journal search uses `Store.query` by requiring ISSN match and optional match on journal name. This prevents the ember app from creating placeholder Journal objects in Fedora when it is not supposed to.
* Data loading for `submissions/new` cleaned up a bit, now that we don't have to pre-load journals.

Search madness

---

app/templates/components/workflow-repositories.hbs
app/templates/faq.hbs

#552 - change wording under "Institutional Repositories" heading a link to FAQ on open access policy. Add FAQ on open access policy.
#556 - change wording on `4. Repositories` to indicate that PASS will help you do a submission to those repositories.

Modify text on Repositories step, adds FAQ on open access policy 

---

app/components/repocopy-display.js
app/components/repocopy-status.js
app/components/submission-repo-details.js
app/components/submission-status-cell.js
app/controllers/submissions/detail.js
app/index.html
app/routes/submissions/detail.js
app/styles/app.scss
app/templates/components/repocopy-display.hbs
app/templates/components/repocopy-status.hbs
app/templates/components/submission-repo-details.hbs
app/templates/components/submission-status-cell.hbs
app/templates/submissions/detail.hbs

#539 
#568 
#582 
Changes are focused in `submission/details`
* Remove old sections: repositories, manuscript IDs, deposits, external repositories
* New display section added intended to consolidate information about repositories, repositoryCopies, and deposits. See ticket for specs
* Update status display in Submissions table
* Revert header fonts

Consolidate submission details

---

app/routes/grants/index.js
app/routes/submissions/new.js

Date filter was not working for Grants lists. This limits the Grant matches to those that have an endDate of after 1/1/2011.
Relates to comment on #572
This is the tail end of PR #590, which was not quite complete and broke the Grants queries

Fixes date filter on the Grants lists

---

app/components/workflow-grants.js

#522 
Change made to the Grant selector in the Grants step of the Submission workflow. Grants are now appended directly to the `newSubmission` object, instead of being stored in a component level variable so that going back and forth in the submission workflow now maintains the changes to the grants list.
* Adding a grant to the submission will remove that grant from the selection list
* Removing the grant from the submission will make that grant visible in the selection list
* If a submission is started _from_ a grant (meaning the grant will be pre-populated in the submission), then that grant will not be visible in the selection list from the start. Removing this grant will behave as expected

Grants selector now updates when grants are added/removed

---

.docker/shib/docker-compose.yml

This contains the broader 7 year Grants load, and 5 years of NIHMS ETL data.

Use latest assets image

---

app/components/workflow-grants.js
app/routes/submissions/new.js

#571 
* Grant list sorted only by `endDate`
* Remove reference to old variable that no longer exists that was throwing errors (`addedGrants` variable)

Apply sorting to grant list in the submission workflow

---

app/controllers/submissions/new.js

#422 
* Start up `.docker/shib` stack as normal
* Login to `ed-user` in order to get some grants that linked to funders with repositories that submissions _must_ be done manually - in this case, US Dept of Education's ERIC
* Start a new submission, pick a grant linked to Dept of Edu such as `Testing the Efficacy of A Developmentally-Informed Coping Power Program in Middle Schools`
* Progress through the rest of the submission workflow, open up the ERIC site, then click Submit to create the new submission.
* After a few seconds (10s max), check in the Submissions table for your new submission. JScholarship should be the only repository shown.

web-link repos and specifically ERIC should no longer be included in new submissions

---

app/routes/grants/index.js
app/routes/submissions/new.js

Use nested bool queries instead of filter and constant_score.
I did some manual testing and it seems to be correct. In order to test look at the grants queries when creating a new submission and when viewing the grants table and make sure pi/copi is matched correctly.

Make queries for grants of pi/copi cleaner.

---

.docker/shib/docker-compose.yml

This includes a change to the `refresh_interval` to make indexing more friendly from the perspective of a user of the Ember app. Should address #492

Update 'indexer' image to include 'refresh_interval' change

---

app/components/workflow-metadata.js
app/components/workflow-review.js
app/controllers/submissions/detail.js
app/templates/components/workflow-review.hbs
app/templates/submissions/detail.hbs

#614 will hopefully be addressed 
Add support for USAID grants in a submission. Previously, these grants were basically ignored in the submission workflow, thus in the submission details page as well. This update will make USAID and other web-link grants behave similarly to Dept of Edu grants: submission will be halted at the review step. Final submission will only be possible after the user clicks a link to the open the web-linked repository (with the goal of having the user manually add a submission).
* Start docker stack as normal
* Login as `ed-user`
* Create a submission with a US Department of Education funded grant
* In the final review step, the Submit button will prompt a user to click the link to the ERIC site, if they have not already done so. Once this link is clicked, the …

Add usaid support

---

app/templates/components/workflow-repositories.hbs
app/templates/faq.hbs
app/templates/index.hbs

* Adds a list of questions to top of FAQ. 
* Fixes scrolling to `#`. Previously links to the questions were scrolling to the wrong place due to the floating header, so this change also adds anchor tags (rather than using an `id` property in the `<h3>` field) that are styled to adjust their top position so that scrolling to the question works properly.
* Fixes some FAQ links. Specifically:
* adds `target="_blank"` to institution policy link in workflow to prevent the user from exiting the workflow to read the policy
* removes link to article processing charges FAQ on welcome page, this FAQ was removed
* corrects link to supported policies on welcome page

Add linked list of questions to top of FAQ page, fix incorrect page scroll

---

app/components/workflow-basics.js
app/components/workflow-metadata.js

`journal-title` property now appears in the blob with `id="common"`. Journal name is pulled from CrossRef, not from our Fedora data (they may be different).
``` javascript
[
{
"id": "common",
"data": {
...
"journal-title": "Some journal name goes here",
...
}
},
...
]
```

'container-title' should now be 'journal-title' in metadata blobs

---

app/routes/submissions/new.js

#630 
Restarting an incomplete submission appended a submission ID as a `submission` URL query parameter in order to pre-populate fields (without needing to know the previous state of the application). If a user were to leave the workflow and start a new submission from the dashboard, the query parameter was kept, so the workflow assumed the other submission was still pre-loaded.
This change clears all query parameters when leaving the submission workflow.
(also fix a code style)

No longer share query params from different places

---

app/components/submissions-repoid-cell.js
app/controllers/grants/detail.js
app/controllers/grants/index.js
app/controllers/submissions/index.js
app/styles/app.scss
app/templates/components/submissions-repoid-cell.hbs

* Change the minimum widths on columns from px to rem so it scales better with font size
* Add min-width to Repositories column on Submissions table
* Add min-width to Date columns on Grants and Submissions table (#604)
* Truncate long manuscript IDs so they don't spill into next column, show full text as title tag (#631)
* Remove anchor tag when there is no URL for accessUrl (something I noticed while doing these other changes)
Manuscript ID before this PR: 
After this PR, a long ID will be truncated like this:
JScholarship IDs will be displayed like this with a popup ID on hoverover (note that this record will have a link in the final system):
To test long manuscript ID: I used latest `pass-docker` with deposit service, DSpace etc. running. I created a new Submission for JScholarship …

Add min-widths to prevent date and repo name wrapping, truncate long manuscript IDs

---

app/components/workflow-files.js
app/templates/components/workflow-files.hbs

Add a note that tells users that files must be smaller than 100MB. If a user tries to upload a file larger than 100MB, alert the user that they have done so, in addition to telling them the name of the too-big file and its size.
* #635

Add file size validation

---

app/components/workflow-files.js
app/templates/components/workflow-review.hbs

This is a hatchet approach for #639. Linking to the files would be more elegant if it's possible, but for now, this prevents the disruption caused by clicking out to example.com mid-workflow and pressing the back button only to have to start over.

Removes example.org url and link from files review

---

app/components/workflow-basics.js

#637 
* Login, etc
* Start new submission however you want
* Try a DOI of your choice
* `abn` is a Method A journal
* `10.1016/j.bpsc.2017.09.006` is another interesting one that has two ISSNs, one Electronic and one Linking
* Go through the rest of the workflow as you wish
* Submit and check the Submission object in Fedora - specifically the big metadata blob
* Metadata blob should include `issn-map` and `nlmta` :: it is possible for neither to be there, if for some reason the external service used to find this information has no record for a given issn.
* `issn-map` should look as described here (no `pub-type:["Linking"]` every) https://github.com/OA-PASS/nihms-submission/issues/122#issuecomment-399545187

Update metadata blob and ignore linking pubtype

---

app/initializers/application.js

#345 
`ember-fedora-adapter` has been updated to throw a specific error when Shib responds with a redirect when session times out. This PR adds a global error handler that will force the current page to refresh when this error is encountered.
_(Kind of optional)_ If you don't do this modification, I think the default session timeout is one hour
* You can modify the `sp` container from `pass-docker` so that the session expires quickly, retag and build the new image.
* `pass-docker/sp/etc-shibboleth/shibboleth2.xml`: `<Sessions lifetime="5" timeout="5" relayState="ss:mem" checkAddress="false" handlerSSL="false" cookieProps="https">` seems to do OK
* `pass-docker/sp/etc-httpd/conf/sp.conf`: any references to `app/` redirection must be removed, as in the `pass-ember` environment, the app sits …

Proposed workaround for shib timeout

---

app/controllers/submissions/new.js

Ember seems to be very ambiguous about how to handle relationships between objects, sometimes resulting in weird errors. While this has no logged ticket, I noticed that new submissions were not appearing in the Submissions table, no matter how long I waited for any indexer update to finish. Turns out that some changes introduced to normalize some code styling broke the way Ember Data saves relationships between objects. Even though Ember models use URIs to reference other model objects, you can't actually set the URI directly, instead it seems Ember expects the full model object.
Bugged behavior created new submission objects with no `user` and no `publication`. File objects were also created for each uploaded file in the submission with no `submission` property.
* Login as whoever you …

Revert some code style changes that were breaking model relationships

---

app/components/submission-status-cell.js
app/components/submission-status.js
app/controllers/grants/detail.js
app/controllers/submissions/index.js
app/routes/grants/detail.js
app/routes/submissions/index.js
app/services/submission-status.js
app/templates/components/submission-status.hbs
app/templates/submissions/detail.hbs
app/templates/submissions/index.hbs
tests/integration/components/submission-status-test.js
tests/unit/services/submission-status-test.js

The submissions table, submissions detail page, and grants detail page have their logic for calculating submission status updated. In addition the submissions table will make a constant number of queries instead of being linear to the number of rows.
Due to limited time, there is code duplication in submissions/index and grants/detail routes as well as in the
submissions-status and submissions-status-cell components.
In order to test. Fire up the app login as various users and look at the submission status.
Note that I am not sure the logic is correct!

Update for submission status

---

app/templates/application.hbs

This is part of proposed integration between static and non-static pages. PASS logo link goes to the static welcome page since the logged in version has some issues to do with timing out and image carousel.
Note that I've left in the original index / welcome route and corresponding test in case we decide to put it back at some point. I just hardcoded links directly on the logo.

Make PASS header point to to static ember page

---

app/components/metadata-form.js
app/components/workflow-basics.js
app/components/workflow-metadata.js
app/components/workflow-review.js
app/controllers/submissions/detail.js
app/services/metadata-blob.js

#655 
* User can now enter author info in the metadata step
* Manually entered article title and journal data is added to the metadata blob
* Manually entered article title and journal info is prepopulated into the metadata step
Addition:
* `issn-map` should not appear in either the submission review _or_ submission details pages
* Load up docker and login as normal
* Start a new submission
* ### **Do not enter a DOI** 
* Enter stuff for _article title_ and select a journal. Click Next
* Progress until you get to the Details step. 
* Article title, Journal ISSN should appear correctly
* User should be able to add authors here (hint: add a user)
* Progress with the rest of the submission
* **Make sure you have your developer tools open for you browser, opened to the Network tab**. This way …

Manually add metadata to submission when not using a DOI

---

app/components/metadata-form.js
app/components/workflow-basics.js
app/components/workflow-metadata.js
app/services/metadata-blob.js

#660
* Don't let user add authors to submission ever
* Don't display 'author(s)' when none exist
This works around the issues found in the ticket by simply not showing the offending pieces :)
* Start a new submission
* DO NOT ENTER A DOI
* Enter an article title and journal
* Progress until the Details step
* **Author(s)** should not appear
* Progress to the review step
* **Author(s)** should not appear
* Submit
* The final metadata blob in the submission _should_ have `authors:[]`
* Check the submission details for the new submission
* **Author(s)** should not appear

Various fixes for metadata display relating to 'authors'

---

app/router.js
app/routes/grants/detail.js
app/routes/submissions/detail.js

Crappy way to check the two `details` paths for unencoded resource IDs. If an unencoded resource ID is found, replace the current browser location with the encoded version.

Try glob matching to grab unencoded grant/submission IDs for the details pages

---

app/services/error-handler.js

This corresponds to a change to add "Unauthorized" to the body of a 401 from the `pass-user-service`.
It has been tested successfully in demo.

Show 401 error if payload is "Unauthorized"

---

app/services/error-handler.js

Previously, the `error.message` would often come back as an unhelpful "undefined". This prints the whole message in the "Something went wrong" box.

Add all error properties to default error msg

---

.docker/shib/.env
.docker/shib/docker-compose.yml

Most notably, this adds the `admin`, and `admin-submitter` users to shibboleth so they can log and have admin and admin+submitter privileges.
Also uses external activemq, and pass authz service, to match `pass-docker`.

Bump Docker images to match pass-docker

---

.docker/shib/docker-compose.yml

The ACL update is a temporary workaround based off of the 6/19 assets image
(containing the 5 and 7 year NIHMS and COEUS loads).  It contains the raw
data from that dump, plus coarse grained ACLs only.
Additionally, the authz updater has been removed until an updated version
is published
This should allow Ember development to cuntinue without 403s untul the
authz updater image is published, and a new assets image is published.
Resolves #698

Update images and point to assets without fine-grained ACLs

---

app/services/error-handler.js

I'm proposing this change for consideration/review. 
Currently, when an unknown error occurs, you click OK and return to the page where the problem originated. This rarely resolves the issue and in fact you often get stuck on the page with the error. I'm proposing this change to reload the app when any unknown error occurs, chances are it will fix the issue.
**The risk of implementation?** (1) That you will get stuck in a error message loop if there is an error that is not fixed by a refresh (2) It refreshes a workflow step and you lose your progress - typically an error indicates things are messed up anyway, but that might not be the perception of the user who experiences this.
**The risk of not implementing?** Users are stuck with errors that may be resolved by a simple refresh
**An …

Add reload on unknown error

---

.docker/shib/.env
.docker/shib/docker-compose.yml
README.md

Changes the Docker shib configuration such that the public (proxied) address for pass is `https://pass.local`, rather than `https://pass`.  
* Edit your hosts file (`/etc/hosts` or `C:\Windows\System32\Drivers\etc\hosts`) to add entry<pre>127.0.0.1               pass.local</pre>
* It might be a good idea to remove the entry for `pass`, since it is going away.
* Go to `.docker/shib`, do a `docker-compose pull` then `docker-compose up`
* Go to `https://pass.local` and verify that the static pages work
* Click on the login link or go to `https://pass.local/app` and log in as your favorite shib user (e.g. `nih-user`).  Verify that the PASS app still appears to work
@karenhanson, @htpvu

Use 'pass.local' as the hostname for shib testing

---

app/components/workflow-review.js

PR to _hopefully_ fix #714, or at least not break it more!  This issue only appeared in demo and presumably production. It was not replicated in `pass-docker` and will therefore only be fully verified by testing in demo.
The main identifiable and relevant difference between running this on `pass-docker` vs running on demo is that demo URLs have periods in them, while `pass-docker` runs at `https://pass`.  In the Ember code, periods can result in attempts to bind objects as if it is dot-notation. 
The change in this PR alters the current approach to updating the `externalRepoMap`. Curiously, there was already a line commented out that will hopefully fix the problem, so this change switches to use that. I have verified that using this other line of code does not break anything.
Using …

Make web linked repositories open correctly in demo

---

app/components/workflow-repositories.js

Fix for issue #720, which was caused by incorrect use of JS `!condition`.
Also, fixed case of `policy.title` used in same condition.
This can be tested using the `usaid-user`, which has both USAID and NIH grants. You also do not need to select a Method A journal specifically - checking to arrange something with the publisher rather than submitting through PASS provides the same effect

Fix if-statement causing incorrect repo assignment

---

app/components/nav-bar.js
app/components/submission-nav.js
app/controllers/faq.js
app/router.js
app/routes/faq.js
app/templates/components/nav-bar.hbs
app/templates/components/workflow-repositories.hbs
app/templates/faq.hbs
app/templates/index.hbs
app/templates/submissions/index.hbs
app/templates/thanks.hbs

This fixes #719.  A script now runs when the workflow navigation bar renders or the top navigation bar renders (which should happen on each new page or workflow step) to set the scroll position to the top of the page.  When going through the workflow or scrolling down the submission page then changing page the user is always returned to the top of the page. This does not affect the scroll when there is a hash in the URL (as with FAQ links).
@htpvu 2 things I wanted to mention. This seems to work, but being unfamiliar with ember I don't know if there is a better way code-wise. Also, note that because the navigation bar tends to load first, sometimes there is a lag in the page content changing when flicking between e.g. grants and submissions - let me know if you think this is unacceptable. …

Added function to scroll to top when navbars are rendered

---

app/components/submission-action-cell.js
app/templates/components/submission-action-cell.hbs

Resolves #750 
This change ensures an action button in `/submissions/` is available if the user logs in needs to take action on a Submission. Specifically:
Submitter:
*  `approval-requested` -> `Review submission` button
* `changes-requested` -> `Awaiting changes. No action required.` message
* `needs-attention` -> `Review submission` button
* `manuscript-expected` -> `Finish submission` button
* All other statuses  -> `No actions available` message
Preparer:
*  `approval-requested` -> `Awaiting approval. No actions available.` message
* `changes-requested` -> `Edit submission` button
* All other statuses  -> `No actions available` message

Refine action buttons to clearly indicate when user can act on a Submission

---

app/components/workflow-basics-user-search.js
app/components/workflow-basics.js
app/styles/app.scss
app/templates/components/workflow-basics-user-search.hbs
app/templates/components/workflow-basics.hbs

Resolves #757:
1. Overrides default modal styling to prevent the top part of the modal going off the top of the page when it does not fit
2. Reduces the number of results displayed from 50 to 40 to help with display issues
3. Changes the wrapping behavior to work for narrower displays.
4. Fixes a typo in a warning box "Nevermind" -> "Never mind"
What is does not address:
1. There is pagination code that does not work. I made some minor changes to it to see if I could get it to work, but there are more issues that will be addressed in a separate issue #761 
2. There is deeper issue with scrolling when a modal is visible. This PR makes it "good enough" to function but ideally the modal would scroll correctly.

Style user search modal

---

app/components/workflow-basics.js
app/templates/components/workflow-basics.hbs

- Remove toaster doi lookup message on next
- Cleanup doi lookup error handling so console is not noisy
- Do doi lookup on mouse actions to handle pasting a doi with the mouse
To test, create a new submission and try to paste in a valid DOI with the mouse. Verify that this works. Before this change, the UI will get stuck because the doi lookup would not get triggered.
Closes #769

DOI lookup fixes

---

app/templates/submissions/detail.hbs

See #758 for details.
In order to test, create a submission using ed-user that will require submission to ERIC. Go through the whole submission and view the details page. Verify that external submissions are displayed correctly.
Closes #758

Fix display of external submissions in detail page

---

app/controllers/submissions/detail.js
app/controllers/submissions/new.js

Assures that Ember always adds a `link` to SubmissionEvents.
Notivication services whitelists need tweaking, so the below instructions do not involve looking at any e-mail messages, and can be attempted in `pass-ember`, or `pass-docker`.
***Feel free to test using https://github.com/OA-PASS/pass-docker/pull/163 instead, as it has this PR incorporated into it, and a lot more things work together.  That would be much more pleasant.***
* Start up Ember's docker, or test in pass-docker
* In incognito mode, log in as `staff2`.  Create a proxy submission, search for user `Kirkwood`.
* Close browser, start another incognito session and log in as `nih-user`.  Look at the submissions table, the first one should be the proxy submission.  Look at it, and request changes.
* Close browser, start …

Set `link` for all submissionEvents

---

app/components/workflow-basics-user-search.js
app/components/workflow-basics.js
app/templates/components/workflow-wrapper.hbs

Going from grants tab to basics tab was removing the submitter value, but simply stopping it from removing the submitter value caused problems with grant assignment. Therefore, as well as stopping the submitter from being removed, this PR includes refinement to the logic when flipping between proxy/non-proxy users. Grants are now always removed at the moment the proxy option is changed or a different user selected. Previously it was sometimes done on clicking next, sometimes when selecting or removing a user.
This PR also simplifies the text on the warning message when grants are being removed.
To test, start a submission, add some grants, go back to the basics tab and try to change the user. It should remove any attached grants when you switch user or proxy option. Try different …

Refine logic for changing users on basics tab

---

tests/integration/components/submissions-status-cell-test.js

When the component name `submission-status-cell.js` was changed to `submissions-status-cell.js` the test name was not updated. This fixed that problem.

Fix test file name

---

app/components/workflow-basics.js
app/components/workflow-metadata.js
app/controllers/submissions/new.js

This pr comments out a check that strips preparers. It is triggered when an approver tries to edit a submission. It is unclear to me what the check was trying to do.
Other changes include more precise checking for a proxy in the new submission route when handling external-submissions metadata and stripping out web-link repositories.

Avoid stripping out preparers, better proxy checking

---

app/components/workflow-basics.js
app/controllers/submissions/detail.js

Enables the spinner (which disables user input) when requesting changes, cancelling, or submitting
Known issues:  #798 prevents certain kinds of testing of this PR.  However, if you submit to _just_ jscholarship, you can successfully make the submission, and see the spinner in that case 
Resolves #800

Enable the spinner in more situations

---

app/components/workflow-basics.js
app/controllers/submissions/detail.js

This changes the popup workflow when a submitter is approving a Submission:
* It no longer shows a blank agreement box and fails when PubMed Central is assigned to the Submission
* The "you are about to Submit.." message now includes all submissions you are submitting to, not just the ones you signed agreementText for.
Closes #798 
Closes #783

Fixed submitter repository approval workflow

---

.docker/shib/docker-compose.yml

Includes a fcrepo verasion that includes support for user tokens, as
well as ldap with additional test users.
Resolves #810

Bring docker images up to date

---

app/controllers/submissions/detail.js
app/templates/submissions/detail.hbs

When a submission does not yet have a submitter uri, the Submission details page was showing "submitter" as blank. This does two things:
1. Displays the `submitterName` and `submitterEmail` when there is no `submitter`. 
2. Removes `institutionalId` as it is no longer available on the User record, and instead displays the `User.email` of the submitter
At minimum, submission details pages for the following 3 scenarios should be looked at:
1. Submission with existing submitter and preparer
2. Submission with new submitter and preparer
3. Submission with manuscript expected status
Close #792

Displays new user submitter name on Submission details page

---

app/components/workflow-basics.js
app/routes/application.js
app/routes/grants/detail.js
app/routes/submissions/detail.js

There is an issue with passing params, this lops off params rather than tries to add them again
resolves #787. 
You can test by passing in the unencoded version of the link with parameters after. For example, before the fix, links like this would have caused files not to load:
* https://pass.local/app/submissions/https://pass.local/fcrepo/rest/submissions/cc/f7/55/87/ccf75587-d828-4458-9deb-d1ed108d3896?userToken=BRO7QA373FK4LPNEJN3TRZUTO2B24EPQ6BHUJOOX3ZOWZEYMXFYRHMPK35THFHHTN4BCLRCXRIKEOX3AOPWCDIRLRCA6DK3LJXGQTSUKWAYZP23IWVMWF5IHQECOMNMVLHOKJTG2LZWNH7DCTZJZPOTYKM6HDJX65TE53ZGFNBYHGOMHPJB3XZET5HPOTFBQ52LHFJQJM24VQCVVNBVRXR5B3FDCATSYRVR7A2CXDP233VFOAIBAOW6LKBTIMGS7CHM4E3U7RHD5H4W2QQX5GUU5JQ
* https://pass.local/app/submissions/https://pass.local/fcrepo/rest/submissions/cc/f7/55/87/ccf75587 …

Encoded uris

---

app/components/workflow-basics-user-search.js
app/styles/app.scss
app/templates/components/workflow-basics-user-search.hbs
app/templates/components/workflow-basics.hbs
package-lock.json
package.json

Previously you could not scroll the modal when parts of the user search modal disappeared off the bottom of the page. To fix this, `ember-tether` module was added to support "tethering" the modal to a page element. Minor style changes were applied (added a min-height).
Also in the PR, when there is only one page of results, the page button is no longer shown.
To test, search for a name that returns a few results, see that page button does not appear, play with the width of the browser window. Then search for a common name such as "robert", note that if you make the page narrow enough for a scrollbar to appear, you can scroll the modal.
Closes #770

Allows you to scroll on the user search popup modal, removes page buttons if one page

---

.docker/shib/docker-compose.yml
app/components/policy-card.js
app/components/workflow-repositories.js
app/models/repository.js
app/models/user.js
app/templates/components/policy-card.hbs

The logic that displays the radio button on the policy page now applies to any policy that uses PMC as its repository. This uses the new `repositoryKey` value, and so an updated `assets` image is referenced with that value populated.
Includes a couple of updates to the model:
* adds `Repository.repositoryKey` - this fix needs the assets container that has these values
* removes `User.institutionalId` (I verified that nothing references this)
* adds `User.locatorIds`
closes #790

Fixes policy page logic to show radio buttons for policies using PMC

---

.travis.yml
app/components/policy-card.js
app/components/workflow-policies.js
app/templates/components/workflow-policies.hbs
app/templates/components/workflow-wrapper.hbs

This changes the policies pages so that if you go back and change the PMC setting for making arrangements with the publisher, it disables tabs after the policy page in order to ensure that the user must step through the workflow and complete the correct repository metadata.
closes #821

When PMC radio button is toggled, disables tabs must use next

---

app/routes/submissions/index.js

Submissions table now sorts by: 
1. submitted asc
2. submissionStatus asc
3. submittedDate desc   
For all fields, if the value is empty they are listed last.
Closes #819

Change sort order on submissions table

---

.travis.yml
app/components/select-row-toggle.js
app/components/workflow-grants.js
app/styles/app.scss
app/templates/components/select-row-toggle.hbs
app/templates/components/submission-funding-table.hbs
app/templates/components/workflow-grants.hbs
tests/integration/components/select-row-toggle-test.js

- Previously a user could select a maximum of 10 grants from a list. 
- Now a paginated table of available results is presented to the user.
- Grants are sorted by descending end date
- The user can click on a row to toggle the grant being associated with the submission.
- The chosen grant list is automatically synced with the table
- Coveralls (used for test coverage check) is turned off in Travis.
The basic functions seem to work. There is probable more to do on styling and layout.
In order to test, try a user with a lot of grants like faculty1, create a new submission, and play with the grants page.
Closes #813

Use a paginated table to select grants during submission.

---

app/controllers/submissions/detail.js
app/styles/app.scss
app/templates/submissions/detail.hbs

This fixes an issue where if a preparer prepares a proxy submission that contains a web linked repository only, the submitter cannot submit it.  For this change, I did some changes to the message that appears to confirm which repositories you are submitting to. It now has some wording for web-linked, please let me know if you want me to change the text. 
Fixed a few minor style issues.
Ideally testing would involve looking at the behavior of hitting "submit" on a proxy submission under various circumstances and making sure it behaves as expected. For example, having the preparer prepare the following and see what happens when submitter submits:
1. submission with web-link repo only (no agreements or other repositories so no repositories attached)
2. submission with jscholarship + weblink …

Fix workflow for web-linked only repos

---

app/components/workflow-files.js
app/controllers/submissions/detail.js
app/controllers/submissions/new.js
app/templates/components/workflow-files.hbs

* Adds validation that requires _exactly one manuscript_ to proceed to 'next' from the file upload page
* Allows file details (role, descriptions) of already-upload files to be editable
* Consolidates all files (pending, and existing) into a unified table
* Places the file upload box at the bottom of the page, as it seemed a more logical location with the above consolidation, except in the case of a proxy submitter intentionally preparing a submission without a manuscript
* Fixes pre-existing bugs and logic errors, including:
* Improper counting of the list of files, which allowed the existing file count check to be bypassed by navigating back and forward
* Wrong constant for supplemental files, resulting in Deposit services failing to deposit any submissions that contained supplemental …

File validation and fixes

---

package-lock.json
package.json

This replaces the deleted `cameronblandford/ember-power-select` with the one from the npm repository.
It looks like this branch was dealing with a testing issue, so hopefully will not affect the function of the application. The grants, user, and journal searches in the submission workflow need to be tested to make sure they are functioning as expected.

Install latest ember-power-select

---

app/routes/submissions/index.js
app/styles/app.scss

* refined sort order on `/submissions/` so that it sorts on `submittedDate desc` before `submissionStatus`. Previously it put submissions with status `submitted` at end of list even if they were most recently submitted. This maintains the sort on unsubmitted since their date is always null.
* widened status column to avoid wrapping

Minor /submissions/ changes

---

app/templates/components/workflow-basics.hbs

This temporarily hides the new user form until we can determine why user tokens are not working in demo
To test create a new submission as preparer and as yourself - note on the basics tab you should no longer have any option to submit on behalf of a user that does not exist yet.

Temporarily hide new user section of Basics workflow tab

---

app/routes/application.js
app/templates/components/workflow-basics.hbs

In the test and demo environments, it [was noticed](https://github.com/OA-PASS/general-issues/issues/85) that e-mail invited users could not see the appropriate submission editing buttons.  This was ultimately traced to Ember not providing the `userToken` to the user service.  The cause of the issue was ember's handling of unencoded URIs.
When Ember encounters an unencoded URI, it needs to encode the embedded fedora resource URI.  A hack was previously in place to do this.  The issue is that this encoding logic ended up erasing any user tokens that were part of the URL.  As a result, the user service was never being sent any tokens.
This PR updates the encoding hack to account for query parameters.  It does this by using a substitution approach, rather than a replacement approach.
First, …

Fix url encoding issue that resulted in deleted user tokens

---

.ember-cli
README.md

Adds `"watcher":"polling"` property to `.ember-cli` to support reloading in Windows.
This should be tested in Windows, but also *nix to ensure it does not break things for other users.
* Follow modified README instructions for starting up `docker`. 
* Once the containers are up, confirm you can load the Ember app and log in
* Change something that you can easily validate through the GUI in the Ember `/app/` folder, observe that the docker ember log reports a change to a file and reloads.
* Hard refresh the page in the browser, you should be able to see your change.

Adds property to support Ember development in Windows, updates README

---

app/components/workflow-basics.js
app/services/doi.js
app/services/nlmta.js
app/services/workflow.js
app/templates/components/workflow-basics.hbs
tests/unit/services/doi-test.js
tests/unit/services/nlmta-test.js

_Do not merge until PR #864 is merged and this is rebased_
This change extracts the code for the DOI lookup and the NLMTA lookup into separate Ember services (doi.js and nlmta.js respectively). Very little was done to the code, this is a copy-paste job to prepare the way for further work on these services.
Also, fixed a reference to the `toastr` service, and switched around some of the code for DOI validation.
Closes #859

Extract out call to crossref and nlmta as services

---

app/controllers/submissions/new.js
app/controllers/submissions/new/files.js
app/templates/components/workflow-basics-user-search.hbs
app/templates/components/workflow-basics.hbs
tests/integration/components/workflow-basics-user-search-test.js
tests/unit/controllers/submissions/new-test.js
tests/unit/controllers/submissions/new/basics-test.js
tests/unit/controllers/submissions/new/files-test.js
tests/unit/controllers/submissions/new/grants-test.js
tests/unit/controllers/submissions/new/metadata-test.js
tests/unit/controllers/submissions/new/policies-test.js
tests/unit/controllers/submissions/new/repositories-test.js
tests/unit/controllers/submissions/new/review-test.js

This PR:
* Adds unit tests to `submissions\new`, and the controllers for its sub-routes.  
* Adds a missing test file for `workflow-basics-user-search`
* Adds some minor changes to `workflow-basics` to support integration test that will be written
* Removes some stray console logs.
Interesting lesson learned: some controllers use the `swal` popup. This will actually popup in tests if not overridden like this, for example:
`swal = result => new Promise(resolve => (assert.ok(true)));`
If we develop these tests in the future, it would be useful to configure the swal property to return different responses (ok, cancel etc). For now, I am submitting as is so that this work can move forward.
Part of #854

Add tests for workflow controllers

---

app/components/workflow-metadata.js
app/services/doi.js
tests/integration/components/workflow-metadata-test.js
tests/unit/services/doi-test.js

Uses properties from metadata schemas to determine which DOI keys to keep, with some custom property mapping. DOI properties that are not explicitly called out in any schema are thrown out as they may be troublesome for JSON schema validation

Autofill doi data

---

app/services/doi.js
app/services/error-handler.js
tests/integration/components/workflow-basics-test.js
tests/integration/components/workflow-metadata-test.js
tests/unit/services/doi-test.js

These changes are meant to address some data weirdness with DOI info coming from Crossref. We were expecting some values to be strings, but were getting arrays of strings instead. For now, we simply join these array values to "stringify" them.

Fix doi data inconsistencies

---

app/controllers/submissions/detail.js
app/controllers/submissions/new.js
app/services/submission-handler.js
package.json
tests/unit/controllers/submissions/new-test.js
tests/unit/services/submission-handler-test.js

This pr pulls out most of the logic surrounding persisting and changing submissions into a service. The pr does not consolidate the logic surrounding popups as in #881.
Tasks:
In order to test, bring up the docker environment and try all of the submission operations: prepare a submission, perform a submission, approve a submission, request submission changes, and cancel a prepared submission. Also try various varieties of file upload.
resolves https://github.com/OA-PASS/pass-ember/issues/896

Refactor submission handling into service

---

app/routes/submissions/new/repositories.js
app/services/policies.js
tests/unit/services/policies-test.js

Closes #915 
Refactor of policy service implementation in Ember to actually return Policy and Repository objects, instead of Promises to those objects. This simplifies the routes greatly, since they no longer need to wait for the promise returned by the service, only to wait for each object's promise.

Policy service now returns fully resolved objects instead of Promises

---

app/components/workflow-metadata.js
app/services/metadata-schema.js
tests/integration/components/workflow-metadata-test.js
tests/unit/services/metadata-schema-test.js

Closes #918 
Note that merging this PR without the DOI service will break the submission workflow!
This PR fixes JSON schema validation during the metadata step of the submission workflow. Each metadata form should not be validated against it's JSON schema properly. Prior to adding the DOI service, ISSN data is received from Crossref, which has publication type information that is different from the values expected by our schemas. This means that any submission with a DOI (that has ISSN data) will be spiked at this point.
Also crucially, this **finally fixes the crazy inconsistent tests for `workflow-metadata`**!!

Fix Schema validation

---

app/services/metadata-blob.js
app/services/submission-handler.js
tests/unit/controllers/submissions/new-test.js

Agreements metadata is added to the blob when a user does their own submission or approves a submission.
In order to test, use the docker environment to perform a submission and approve a submission. Check the metadata blob in both cases for the 'agreements'.
Closes #908

Add agreements to metadata blob

---

app/components/submission-repo-details.js
app/components/workflow-metadata.js
app/components/workflow-review.js
app/controllers/submissions/detail.js
app/models/repository.js
app/services/metadata-blob.js
app/services/submission-handler.js
app/templates/components/nav-bar.hbs
app/templates/components/submission-repo-details.hbs
app/templates/submissions/detail.hbs
tests/integration/components/workflow-review-test.js
tests/unit/controllers/submissions/new-test.js
tests/unit/services/submission-handler-test.js

Closes #924 
Removes a legacy `external-submissions` property from the metadata blob that would not pass schema validation

Remove 'external-submissions' from metadata blob

---

app/services/metadata-schema.js
tests/unit/services/metadata-schema-test.js

Closes #936 
A single very quick submission suggested that this fix at least adds DOI to the metadata blob. Unit tests and probably more testing is required to verify.
This takes the first approach outlined in the ticket to automatically try to inspect the given set of schema for properties to add.

More properties should be added to the list of 'valid' fields to take from Crossref

---

.docker/docker-compose.yml
app/styles/app.scss

Closes #938 
Streamlines some of the layout issues in the metadata forms.

Update metadata forms layout

---

.docker/.env
app/services/policies.js
config/environment.js

Closes #942 
I was able to see configuration changes in the UI, but only after refreshing the `ember` dev image, which, I believe, rebuilds the development site

Let policy service URL be configured

---

.ember-cli
app/components/display-metadata-keys.js
app/components/submission-action-cell.js
app/components/workflow-basics.js
app/components/workflow-files.js
app/controllers/submissions/detail.js
app/controllers/submissions/new/basics.js
app/models/journal.js
app/models/submission.js
app/routes/submissions/new.js
app/services/error-handler.js
app/services/submission-handler.js
app/services/workflow.js
app/templates/components/submission-action-cell.hbs
app/templates/components/workflow-basics.hbs
app/templates/submissions/detail.hbs
app/templates/submissions/new/basics.hbs
tests/integration/components/workflow-basics-test.js
tests/integration/components/workflow-files-test.js
tests/unit/controllers/submissions/detail-test.js
tests/unit/controllers/submissions/new/basics-test.js
tests/unit/routes/submissions/new-test.js
tests/unit/services/submission-handler-test.js

Closes #905 
------
_Reopening this PR from the `pass-ember` repo, instead of from my fork so that other people can make changes._
_Only limited tests so far._
_My biggest concern is the way Journal data is loaded in the case of a draft submission with a Publication with no DOI. This is handled similarly to how DOI would be loaded into the widget: if applicable, it will send the `selectJournal` action to kick off it's logic and add the Journal metadata to the workflow service. Applicability here is if a Journal object is passed to the component from the `submission/new` route, which should happen only when loading draft submissions._
------
* Of course, the "Edit" button for draft submissions is now enabled
* Publication objects now persist after the workflow basics step
* This fixed a …

Reenable draft edit

---

app/components/workflow-basics.js
app/templates/components/workflow-basics.hbs
tests/integration/components/workflow-basics-test.js

Closes #944 
This was a little more convoluted that I had hoped. We do need to invoke the DOI service if submission metadata is empty or invalid. For draft submissions that already have a Publication, but no valid metadata, we must make the call to the DOI service, but ignore the Publication object that it returns. Even though the returned Publication object will have identical contents to the object already on the submission, we want to prevent the creation of duplicate objects in Fedora. By ignoring the Publication object from the DOI service, the Publication object is created on the client side, but never persisted to the back end.
`#lookupDOI(setPublication)` this function signature has changed to include a boolean argument telling whether or not the publication returned by the DOI …

DOI lookup happens if draft submission has empty metadata

---

app/components/workflow-repositories.js

Closes #931 
* Progress through the submission workflow
* Finish the Repositories step, click Next (this will persist changes)
* Click Back button OR click the Repositories tab to go back to that step
* Bad things happen
This bug may also occur if you finish the Repositories step, go back to a previous step, like Basics, then progress forward again to get to the Repositories step.

Navigating between repo tab and others shouldn't break things anymore

---

app/controllers/submissions/new.js
app/routes/submissions/index.js
app/services/search-helper.js
app/services/submission-handler.js
tests/unit/routes/submissions/index-test.js
tests/unit/services/search-helper-test.js

Closes #955 
A shared service is created that can be used to maintain an "ignore list" that can be referenced before and after a route transition. This is sometimes necessary because of the lag time of reindexing in Elasticsearch.
This work focuses on "Aborting" draft submissions from the workflow. The draft submission is added to the ignore list, then this list is seen by the `submissions` route and added to the ES query to prevent the given ID from appearing in the ES results.

First draft at polling ES for changes

---

app/controllers/submissions/detail.js

Closes #961 
Uses the `search-helper` (should rename) to ignore the newly deleted submission so that it does not appear in Elasticsearch results before ES finishes indexing.
The ignore list is already being checked in the submissions table due to a previous PR adding this change to the "Abort" button in the submission workflow

Submissions deleted from details page shouldn't reappear

---

app/components/workflow-basics.js
app/components/workflow-metadata.js
app/services/doi.js
app/services/metadata-schema.js
app/services/workflow.js
app/templates/components/workflow-basics.hbs
tests/integration/components/workflow-basics-test.js
tests/integration/components/workflow-metadata-test.js
tests/unit/services/metadata-schema-test.js

Closes #939 
Also Closes #965 
One caveat is provided in the ticket. Alpaca warns about invalid data for _Authors_ and _ISSNs_. This doesn't seem to effect the metadata that gets saved to the submission.
`workflow-metadata` now assigns all keys that appear in the incoming metadata as read-only. When these keys are encountered in any rendered schema, they are marked as read-only in Alpaca. This implementation seems to work for submission with and without DOIs.
This example test case should exercise basically everything, so is extensive:
1. Start new submission
2. Enter a DOI, example: `10.1039/c7an01256j`
* There should be a (hopefully) brief popup in the top right saying that we're looking up your DOI
* The Next button should be greyed out while the DOI is loading
* After the DOI loads, …

Set metadata provided to metadata step as readonly in forms

---

app/components/workflow-basics.js

PR title is fairly self explanatory. Publication data is supposed to clear when the user clears deletes the DOI. There was a bug that prevented this from happening by skipping the call to the DOI service

Fix an issue preventing DOI data from clearing sometimes

---

.docker/docker-compose.yml
app/components/workflow-metadata.js
app/services/doi.js
app/services/metadata-schema.js
tests/integration/components/workflow-metadata-test.js
tests/unit/services/metadata-schema-test.js

Closes #964 
This implementation relies on an updated schema service, as it changes `publicationDate` to a string, from a date format.
* Map crossref `issued['date-part']` field to `publicationDate`
* Temporarily bump schema service version, will be updated once the new version is released
This is actually in a state that can be tested, simply pull these changes, bring up the `pass-ember` docker environment, start a new submission with a DOI of your choice, proceed through the submission workflow. Publication date should now appear in the metadata forms, and it should not trigger any validation errors.

Grab publication date from DOI data

---

.docker/docker-compose.yml
app/components/workflow-metadata.js
app/services/metadata-schema.js
tests/integration/components/workflow-metadata-test.js
tests/unit/services/metadata-schema-test.js

Closes #968 
* Schema service will now try to get merged schema, then retry unmerged schemas on failure
* Schema `title` no longer displayed if there is only a single schema to show - this _should_ happen only if schemas have been merged

Update schema service to use merged schema when possible

---

app/components/workflow-basics.js
app/components/workflow-metadata.js
tests/integration/components/workflow-metadata-test.js

Closes #976 
Previous behavior as described in the linked ticket had stale data from a previous run through the workflow appear in the metadata forms of a new submission that had no DOI. This was ultimately caused by somewhat faulty logic used to purge the metadata.
Steps to test can be seen in the linked ticket.

Stale metadata no longer appears in workflow

---

app/controllers/grants/detail.js
app/templates/grants/detail.hbs

Closes #959 
I ended up simplifying some references in the grant details template by providing a `grant` alias.
We don't have test data to test this.

Display coPIs correctly

---

app/controllers/grants/detail.js
app/templates/grants/detail.hbs

Computing the display string in the controller was buggy due to how Ember was (not) loading objects in the `coPis` array. Moved logic back to the template.
I would normally have had the `{{each}}` and `{{if}}` declarations on separate lines for readability, but this was adding an extra white-space to the rendered page.

Update coPIs list in grant details again

---

app/routes/grants/detail.js
app/routes/grants/index.js

Closes #979, #984 
Update ES queries in the routes for the grants table and grant details page to explicitly ignore any submission the `submissionStatus: 'cancelled'`

Update queries to ignore cancelled submissions

---

app/components/workflow-basics.js
app/templates/components/workflow-basics.hbs

Closes #986 
Errors are now displayed more plainly to the user when bad things are returned by the DOI service (bad things such as service error messages, or Crossref errors). Error messages now displayed under the DOI input field, instead of a Toastr popup in the top corner

Modify error handling for DOI service

---

app/styles/app.scss

Previous CSS rule actually didn't effect spacing between radio input and label

Add spacing between Alpaca radio input and label text

---

app/components/workflow-grants.js
app/components/workflow-repositories.js
app/routes/submissions/new/policies.js
app/services/submission-handler.js
app/services/workflow.js
tests/integration/components/workflow-repositories-test.js

Closes #982 
This issue ballooned out a bit, addressing not only `submission.effectivePolicies` not being updated, but also `submission.repositories` not being updated properly. As described in the ticket, this occurred when the user goes through the workflow, then goes back to change the grant selection. It also shows up when editing a draft submission and the user changes the grant selection.
* workflow service: Can now be used to track grants that are added to the submission. Since data here only survives through one pass through the submission workflow, this information can be compared to the grants list on the submission to determine whether a grant was recently added.
* grants step: the Grants step now adds the grant to the workflow service, as well as the submission object. This …

Address inconsistencies with adding grants

---

app/services/workflow.js

This only fixes part of #995 when a user _removes_ a grant using the Remove button provided in the top table of the Grants step. Toggling a grant off (or on for that matter) from the grants selection table is still broken because the grants selection table uses a different mechanism to add/remove grants that skips that tracking needed to recalculate repositories. This is basically step 1 in a larger fix.
This fix will correct the bug listed in the linked issue: When the user goes back in the workflow and removes the NIH grant as described in the issue (assuming they do so by clicking the Remove button), this change will now correctly prevent the user from skipping forward in the workflow, thus avoid the error seen.

Fix typo preventing grant adding from working as intended

---

app/components/workflow-grants.js
app/services/submission-handler.js
app/templates/components/workflow-grants.hbs
tests/integration/components/workflow-grants-test.js

Closes #995 
A few changes, mostly around the `workflow-grants` component.  It was found that toggling grants on and off the submission using the "grant selection table" in the Grants step of the workflow did not use the add and remove actions in the `workflow-grants` component. Because of this, unintended behavior could occur  when modifying grant selection. 
It was intended that when the grants selection changed, that forward navigation would be restricted to the user, forcing them to step through subsequent steps in order for various properties to be calculated and added to the submission correctly. Because of the other mechanism used by the "grants selection table" to toggle grants on or off the submission, this navigation restriction was not enforced in some cases, allowing the user …

Tracking grants, take two

---

.docker/docker-compose.yml
app/components/metadata-form.js
app/components/workflow-metadata.js
tests/integration/components/metadata-form-test.js

Closes #1001 
Changes:
* Update schema service version
* Make sure empty array values in Alpaca are not counted in metadata, otherwise validation will not work
* Don't escape HTML in error messages

'authors' property now required for J10P

---

app/controllers/submissions/detail.js

When a _submitter_ goes to review a prepared submission and approves it in the submission details page, the `Review, Request Changes, Edit, Cancel` buttons would stay on the page.
* The UI flag that toggled the visibility of these buttons now tracks the appropriate model property
In order to create a proxy submission, see these instructions: https://github.com/OA-PASS/pass-ember/wiki/Testing-Proxy-Submission
To test this PR
* login as the _submitter_ and review the submission
* Click the Submit button
* Click through the various prompts
* See if inappropriate buttons are on page

Proxy sub review buttons should now disappear correctly after approving the submission

---

app/components/workflow-files.js
app/services/doi.js
app/services/submission-handler.js
tests/integration/components/workflow-files-test.js
tests/unit/services/doi-test.js

Closes #1004, #1006 
* Made adding a journal to submission more defensive to prevent errors when adding a journal that has no ISSNs
* When files are removed from a submission during the workflow, the reference to the submission on the Files object itself is now removed, preventing this file from reappearing on the submission
* This approach was taking instead of fully deleting the File from Fedora because last time we tried to issue DELETE operations, we would get weird permission errors in TEST
* Start a new submission
* Manually enter info: any title, and a journal with no ISSN
* Example: `Bulletin. Moore-White Medical Foundation, Los Angeles`
* Progress through workflow until you get to the Files step
* Add a file as the `manuscript`
* Remove that file, then add another file as the …

Handle journal without issns

---

app/components/workflow-files.js

Make sure that files that have just been added to the submission can be removed as well. This is necessary because there is an artificial distinction between files that existed on a submission from before/after the start of the workflow. This means that files already on a draft submission before the start of editing are treated differently from files that have been added to the submission during the editing workflow.

Fix removal of 'new' files

---

app/services/metadata-schema.js
tests/integration/components/workflow-metadata-test.js

Closes #1009 
This PR tries a workaround for an issue dealing with Alpaca's `(required)` labels that it automatically adds to _required_ fields. The linked issue describes how child fields of an array field will automatically gain `(required)` labels if the parent array field is marked as _required_ in the schema. It was determined that this only seems to occur when array data is pre-loaded into the Alpaca schema prior to rendering. This workaround simply removes the _required_ status of the parent array field IFF it has data to pre-load. This change only effects the schema meant for Alpaca rendering, thus should not effect any JSON schema validation.
Still needs some tests

Workaround the double (required) labels

---

app/components/workflow-basics.js
app/templates/components/workflow-basics.hbs

Closes #1034, #1035 
* No longer escape HTML in error message
* Fix grammar mistake in pending DOI message
To test, first make sure you don't have another Docker stack running. Pull these changes, navigate to the `.docker/` directory, then run `docker-compose up -d` and optionally run `docker-compose logs -f` to monitor Docker. Start a new submission and try messing with the DOI input field to see what happens.

Fix some DOI related user messages

---

README.md

Let's a developer know that there is a second development stack that can be used to emulate the distinct Harvard PASS instance

Add instructions on how to run the Harvard stack

---

.docker/ember-dev/Dockerfile
.ember-cli

- node >= 10 is required for the ember upgrades
- this updates the Dockerfile with the method of installing node / npm as is done in the official node docker image https://github.com/nodejs/docker-node/blob/d071b895dd1b8da6c566f45b971825fe5b087b21/10/alpine3.9/Dockerfile

Fix docker w yarn

---

app/components/covid-selection-banner/template.hbs
app/components/found-manuscripts/component.js
app/components/found-manuscripts/template.hbs
app/components/workflow-files.js
app/services/oa-manuscript-service.js
app/styles/app.scss
app/templates/components/workflow-files.hbs
config/environment.js
mirage/routes/files.js
tests/acceptance/nih-submission-test.js
tests/integration/components/found-manuscripts/component-test.js
tests/integration/components/workflow-files-test.js
tests/unit/services/oa-manuscript-service-test.js

- this removes the use of sweet alert to provide loading state
- it moves loading state inline into the file list
- handles cancellation of upload inline as well
- this makes a few minor tweaks to support multiple files
TODO:

adds cancellation refinement to download manuscripts component

---

app/components/found-manuscripts/template.hbs
tests/integration/components/found-manuscripts/component-test.js
tests/integration/components/workflow-files-test.js

Fixes #1078 
* Add message to user when no OA manuscripts are found
* Previous behavior was to show nothing, leading to inconsistent messaging
* Display full file URL, instead of file name to disambiguate files with the same name
* Use DOI: `10.1039/c7an01256j` to check the _Files_ step when with a DOI that has no OA manuscript files
* Use DOI: `10.1038/nature12373` to check behavior with a DOI that has more than one OA manuscript file

UPW bugfixes

---

app/components/workflow-files.js
app/templates/submissions/detail.hbs

Fixes #1079 
* Adds a message to the user on the details page for a submission showing if a submission is related to COVID research

Show a message for COVID submissions

---

app/components/workflow-review.js
tests/acceptance/nih-submission-test.js

This is a Draft PR because there are no automated tests yet to check for this issue.
The issue seems to be caused by a lack of handling of cancellations of the SweetAlert popups in the Review step.
When a user clicks the Submit button, an element is made visible that blocks all user interaction with the UI. In "normal" submissions, this is handled after the submission is completed. However, if a user cancels out of the agreement popup, or doesn't click the Agree checkbox, the popups will disappear as expected, but this blocking element will never be removed. The user now cannot interact with the application.
Please feel free to take ownership of this PR and mark as ready for review when it's good to go.

Fix bug causing UI to be unusable if review popup was cancelled

---

app/routes/application.js

Work around issue where application tries to access a submission whose id is not encoded in the URL and double slashes after https: have been turned into a single slash. Ember is responsible for the slash compression.
In order to test, create a submission and try to access with the id portion of the URL unencoded.
See #1086

Handle unencoded submission ids without double slashes

---

app/components/workflow-basics.js
app/controllers/submissions/detail.js
app/models/submission.js

- due to some surprising behavior based on the type of submitterEmail field in fedora (@id not a string), sending an empty string to fedora for this field will result in the submission resource being set as the value
- this occured when making a proxy sub on behalf of an exisiting user
- to avoid this we should always send a null value (rather than empty string) if we do not intend for fedora to set this field
- this allows for the field to be null'able and sets a default value as null on the model and explicitly in certain areas where the value was being set to an empty string
- this also cleans up the computeds on the submission detail to watch the correct properties so they're populated corretly once promises are resolved
Addresses: https://github.com/OA-PASS/general-issues/issues/142

Fix submitter email bug

---

app/components/workflow-grants/index.js

- some references to updateGrants in the pagination controls were not using task syntax rendering the buttons unusable
- this updates to use task perform helper

Fix grants table pagination

---

.husky/pre-commit
README.md
package.json

Addresses: https://github.com/eclipse-pass/main/issues/228
- this runs the husky init cmd which is required to make husky work
- this adds the lint-staged cmd to the husky pre-commit file
- this also updates what cmds are run by lint-staged to include prettier
and gets rid of the unrelated file types
This is an example of what would happen if you attempted to commit something that violates an es-lint rule. Here I added a debugger intentionally and tried to commit it:

Fix husky setup

---

.github/workflows/node.js.yml
package.json
yarn.lock

What's in this PR:
- this updates the lock file to include the upgraded version of husky (was left out of a prior PR)
- this fixes the Github action so that ember tests run in CI
- this upgrades the only forwards compat dep in the repo

Upgrade fwd deps

---

app/models/contributor.js
app/models/deposit.js
app/models/file.js
app/models/journal.js
app/models/publisher.js
app/models/repository-copy.js
app/models/repository.js
app/models/submission-event.js
app/models/submission.js
app/models/user.js
app/routes/dashboard.js
app/transforms/enum.js

* New 'enum'-like attr type for select attributes
* Custom 'enum' transform
* Update appropriate models to use the new type
Notes:
* `store.query` filters still must use the UPPER_SNAKE_CASE values, as they are currently passed directly to the backend
* Enum exports from model files are maintained for reference. We can remove these if necessary

Using enums

---

app/adapters/application.js
app/authenticators/http-only.js
app/components/nav-bar/index.js
app/routes/check-session-route.js
config/environment.js
mirage/config.js

- setting the host in the adapter is unnecessary because ember will default to the current host by default, which is more flexible than requiring it to be set
- this removes the setting of host
- this also fixes an issue with passthrough which were not capturing fully qualified domains
- some misc cleanup as well

Fix host and passthroughs

---

app/adapters/application.js

- the session service wasn't being injected which meant `session.invalidate` was never being called
- this caused two bugs:
1) stale sessions would hang on network interactions after becoming stale and the error handler service would trap things in the modal;
2) a re-authentication after this hang would further hang when hitting the `auth/callback` route (probably because the client side session was still in place.
- injecting the session allows the session to be invalidated properly

Fix stale session hang bug

---

app/components/workflow-basics-user-search/index.js
app/routes/grants/index.js
app/routes/submissions/index.js
app/services/autocomplete.js

Resolves https://github.com/eclipse-pass/main/issues/372
A few JSON:API filters needed to be grouped correctly with parenthesis. Some JSON:API filter parts needed to be surrounded by double quotes, if a space could appear in the filter string.
* Submission workflow, Basics step, user search
* Grants list page
* Submissions list page
* Journal autocomplete search
Submissions list page also was not matching against `preparers`

Fix som JSON API filters

---

app/authenticators/http-only.js
app/routes/auth-callback.js

- re-authenticating, when a valid client side session exists, was causing the UI to hang at auth-callback
- this fixes that by side-stepping the authenticator if there's a client-side session and a valid server-side session
- this also ensures that validating client-side session data is matched against the server-side session
Addresses: https://github.com/eclipse-pass/main/issues/379

Fix stale auth bug 2

---

.github/workflows/release.yml

* Move all git pushes to end of workflow
* Push to the branch specified in the manual workflow trigger instead of to `main` always

Push release commits to the right branch

---

.github/actions/build-pass-ui/action.yml
.github/workflows/release.yml
build.sh

"Build" action can be told to build dev or prod artifacts. Dev build is default behavior, Release workflow updated to make "prod" image for full release, but dev version for any -snapshots

Snapshot versions should build dev images

---

.github/actions/build-pass-ui/action.yml
build.sh

Will ignore the newish env vars from pass-docker that start with PASS_CORE_POLICY. They are not used by pass-ui, so not needed during the build

Workaround error exporting .env file

---

app/components/workflow-review/index.hbs
app/controllers/submissions/new.js

- our catch block for the submission review step was previously not being hit
- a new issue with submissions exposed that we were calling an invalid method on `this.flashMessages` (i.e. `error` instead of `danger`).
- this addresses that issue

fix: fix flash messages

---

ember-cli-build.js

- we need to not fingerprint assets for now or it will break the theme'ing (we'll fix that later)
- we also need to not strip the data test selectors because test cafe relies on them

fix: enable prod builds

---

app/components/repository-card/index.js
tests/integration/components/workflow-repositories-test.js

- checking/unchecking the optional repo on the repositories step was not working
- this removes preventDefault which was interfering with the native browser interaction
- this adds assertions to tests in this area that weren't previously covered
- partially resolves https://github.com/eclipse-pass/main/issues/656

fix: toggle optional repo

---

app/routes/submissions/index.js

- in order to display manuscript IDs on a fresh load of the submissions index page we need publications to be loaded as well
- this includes publications with the submissions fetch
- partially addresses: https://github.com/eclipse-pass/main/issues/656

fix: submission index manuscript id loads

---

app/components/workflow-basics/index.js

- when editing a submission we call selectJournal which calls updateDoi during the render cycle causing the bug
- this uses scheduleOnce afterRender to fix that
Closes: https://github.com/eclipse-pass/main/issues/691

fix: edit submission bug re missing doiInfo

---

app/styles/app.css
public/branding.css

- this makes the proxy sub card background the same as the steps background and the font black
- this should make the links visible and allow most branding to have links to emails that will pass accessibility tests
Closes: https://github.com/eclipse-pass/main/issues/693

fix: proxy submission card colors are conflicting with branding

---

app/templates/thanks.hbs
public/branding.css

closes: https://github.com/eclipse-pass/main/issues/706

fix: make thanks links more prominent

---

app/styles/app.css

Closes: https://github.com/eclipse-pass/main/issues/704
Closes: https://github.com/eclipse-pass/main/issues/705
For some unknown reason the FontAwesome glyphs aren't rendering any more. This moves to using unicode chars instead.

fix: metadata step glyphs

---

app/models/submission.js
tests/unit/services/submission-handler-test.js

This is support optimistic locking with Submission/Deposit.  I didn't add the `version` attribute to Deposit because it doesn't appear Deposits are saved from the UI.
https://github.com/eclipse-pass/main/issues/715

[pass-ui] Submission and Deposit optimistic locking

---

app/components/metadata-form/index.js
app/services/metadata-schema.js
tests/acceptance/nih-submission-test.js
tests/integration/components/workflow-metadata-test.js

Closes: https://github.com/eclipse-pass/main/issues/710

fix: hidden authors fields in metadata schema step

---

app/components/notice-banner/index.hbs
app/components/notice-banner/index.js
tests/integration/components/notice-banner-test.js

This PR externalizes the instruction URL in the notice banner to the config.json so it can vary by env.
https://github.com/eclipse-pass/main/issues/690

Externalize instructions Url to config.json

---

app/components/workflow-basics-user-search/index.js

This pr corrects the pagination with elide and makes sure we grab the total pages from the meta block of the result.
In addition the user query is normalized so that special characters don't make the query invalid.

Fix pagination of proxy user search component

---

app/controllers/application.js
app/routes/application.js

Makes sure the user service gets called once if the userToken parameter is provided before everything else. The service may modify submission objects in the backend.
This also removes the weird route munging which was needed because of proxy url encoding issues and is no longer needed.

Call user service with a userToken parameter

---

app/components/workflow-basics-user-search/index.js

Now multiple non-alphanumeric characters in the search string become a single space. In addition space is trimmed off the ends of the string. So now searching for "Mark+=Patton" and "Mark Patton" and "  Mark   Patton " will all be normalized to "Mark Patton".

Correctly handle whitespace when normalizing proxy user queries

---

app/components/workflow-basics/index.hbs
app/components/workflow-basics/index.js
app/components/workflow-metadata/index.hbs
app/components/workflow-metadata/index.js
app/controllers/submissions/new/basics.js
app/services/doi.js
tests/unit/controllers/submissions/new/basics-test.js

Need to test submission with and without a journal to PMC and Dspace.

Make journal selection optional

---

app/components/policy-card/index.hbs

Closes: https://github.com/eclipse-pass/main/issues/772

fix: remove link in header from from policies cards

---

app/components/submissions-award-cell/index.hbs
tests/integration/components/submissions-award-cell-test.js

Now br html element will be processed as an HTML element and not displayed as text.
https://github.com/eclipse-pass/main/issues/783

Fix br html element rendering bug

---

app/components/workflow-review/index.css
app/components/workflow-review/index.js
app/styles/app.css
tests/acceptance/nih-submission-test.js
tests/integration/components/workflow-review-test.js

Closes: https://github.com/eclipse-pass/main/issues/402

fix: deposit requirement modal copy

---

app/components/workflow-basics/index.js

If you paste in a valid doi and then just mess with it by adding  or deleting a character, you get an error popup. This is just caused by a bug handling the error message.

Fix bug displaying error message when doi lookup fails

---

app/components/submission-nav/index.hbs
app/controllers/submissions/new/basics.js
tests/acceptance/nih-submission-test.js

Closes: https://github.com/eclipse-pass/main/issues/763

fix: publication title not updating after amending it

---

app/controllers/grants/detail.js
app/controllers/grants/index.js
app/controllers/submissions/index.js
app/routes/grants/detail.js
app/routes/grants/index.js
app/routes/submissions/index.js
app/templates/grants/detail.hbs
app/templates/grants/index.hbs
app/templates/submissions/index.hbs
app/util/paginated-query.js
tests/acceptance/nih-submission-test.js
tests/unit/controllers/grants/index-test.js
tests/unit/controllers/submissions/index-test.js
tests/unit/routes/grants/detail-test.js
tests/unit/routes/grants/index-test.js
tests/unit/routes/submissions/index-test.js

(Will) Close https://github.com/eclipse-pass/main/issues/547
* Grants list pagination largely working, global filter not hooked up
Adding support for server-side pagination, where previously we grabbed all records and did client side paging. For now, I've added some URL query params: 
* `page` [integer] : current page to show
* `pageSize` [integer] : number of items per page
* `filter` [string] : global search string to narrow items shown on the page
* Currently only over `grant.projectName`
These query params will be automatically added to the URL and updated as the user uses the pagination controls, but the user can also manually update these parameters in their address bar, if desired
* Should investigate using an index for this in a separate PR
* ~[ ] Add pagination to the grant …

Adding server-side pagination support

---

app/controllers/not-found-error.js
app/templates/not-found-error.hbs

Fixes https://github.com/eclipse-pass/main/issues/806
Update 404 page to handle missing contact link
* Get rid of the template string, which would report undefined values as string literal `'undefined'`
* Message when URL is undefined changed to "Please contact your administrator"
* Is it fine to get rid of the stand alone `get` in this context?
* Update 404 page template
* Don't add link if contact URL is not defined
* Small restructure

Fix bad URL in contact link on 404 page

---

app/components/external-repo-review/index.hbs
app/components/external-repo-review/index.js
app/components/workflow-repositories/index.hbs
app/components/workflow-repositories/index.js
app/components/workflow-review/index.css
app/components/workflow-review/index.hbs
app/components/workflow-review/index.js
app/controllers/submissions/new/repositories.js
tests/integration/components/external-repo-review-test.js
tests/integration/components/workflow-repositories-test.js
tests/integration/components/workflow-review-test.js

[Will fix] https://github.com/eclipse-pass/main/issues/815
**Pending redesign and new wording approval**
* `web-link repository`: repositories that PASS can't integrate with. PASS cannot make a submission on behalf of our users to these repositories. Instead, the users must go to these repositories and manually create their own submission.
* Repositories step
* Break out web-link repositories into separate section with brief description
* Review step
* web-link row moved to the top
* web-link row text colored red, links bolded. Color changes to black, links unbold when the user visits the links
* Submit button disabled until all web-links are visited
* Other minor UI tweaks
* Bullet points in repository lists removed
* Spacing of repository lists normalized
* Weblink repository names AND …

Clarify PASS support of web-link repositories

---

app/adapters/file.js
app/components/workflow-files/index.js
mirage/config.js
tests/integration/components/workflow-files-test.js

Resolves https://github.com/eclipse-pass/main/issues/514
- Update the `deleteFile` function in the Files step to call the file service to delete the file, then delete the File object in the DB
- Add console log in the same place to print when an error occurs
- Updates to tests
- Check to make sure `file.destroyRecord` is called
- General test code updates

Delete files when removed from Draft submissions

---

app/services/metadata-schema.js
tests/integration/components/workflow-metadata-test.js
tests/unit/services/metadata-schema-test.js

Resolves https://github.com/eclipse-pass/main/issues/876
- Converts proxies where necessary with `toArray()`
- Prevents REST call when no or empty args passed to service

UI shouldn't send empty requests to metadata schema service

---

app/adapters/file.js
app/components/workflow-files/index.hbs
app/components/workflow-files/index.js
mirage/config.js
tests/integration/components/workflow-files-test.js
yarn.lock

Could use an eye on error handling.
Error handling in general is a bit of a mess in pass-ui, but specifically for file deletion, we want to try to handle error cases where the File entity could get into a weird state:
- Deletion of the file bytes has to be handled separately from removal of the File (metadata) entity in the database
- File entity has a URI reference to the bytes, pointing to where the file service can operate on the file
- Getting these two out of sync could be problematic in the Files step, submission review page, or submission details page
- Provide custom File model adapter:
- Call to `FIle.destroyRecord` will delete file bytes via the File Service before calling standard `destroyRecord` in the Ember store
- Update/add tests for `workflow-files` component

File deletion v2

---

app/components/submission-action-cell/index.js
app/controllers/submissions/detail.js
app/routes/submissions/new.js
app/services/submission-handler.js
app/util/paginated-query.js
tests/integration/components/submission-action-cell-test.js
tests/unit/controllers/submissions/detail-test.js
tests/unit/services/submission-handler-test.js

Related: https://github.com/eclipse-pass/main/issues/549
pass-core PR: https://github.com/eclipse-pass/pass-core/pull/81
Will require some pass-core changes to add delete permissions on appropriate objects
- Update submission delete logic:
- Delete Files on a draft submission
- Delete Publication when possible
- Finally, delete the Submission
- Errors either thrown directly or passed
- Update `submission-action-cell` which has a Delete button
- Add flash message on submission deletion error instead of relying on default error handling
- Update submission deletion logic in submission details page to show a flash message on submission deletion error
- Normalize behavior to match behavior with submission-action-cell

Submission deletion 

---

app/routes/application.js
app/routes/check-session-route.js
tests/acceptance/app-test.js

Fixes https://github.com/eclipse-pass/main/issues/929
- Move static config loading from `afterModel` hook to `beforeModel` hook
- Force waiting for this to resolve before proceeding with any/all routes to avoid errors in those routes when trying to access the config
- Add basic regression test to make sure routes outside of root load directly
- Also add a `console.error` to dump error messages into JS console in browser on route/model hook errors
- The error case presented by this bug should at least be dumped into the browser console with this
- You'd need to create a local build of this branch of `pass-ui`
- The included `build.sh` can help: `> ./build.sh <path_to_pass-docker>/.env`
- This will produce a new Docker image: `ghcr.io/eclipse-pass/pass-ui:latest`
- In …

Force config loading at application root

---

app/routes/check-session-route.js

- The UI was sending a request to whoami on every route visit
- This avoids that by only authenticating if a session doesn't already exist

refactor: don't call authenticate on every visit to check session

---

app/authenticators/http-only.js
app/routes/check-session-route.js
mirage/config.js
package.json
tests/acceptance/session-test.js
tests/unit/authenticators/http-only-test.js
yarn.lock

Closes: #https://github.com/eclipse-pass/main/issues/974

fix: session data shape bug

---

.github/workflows/ci.yml
.github/workflows/update-docker-image.yml

Needed for complete workflow fixes PR: https://github.com/eclipse-pass/main/pull/983
Updated ci workflow to trigger on same events as pass-core/pass-support.
Changed update docker images workflow to trigger on PR merge.

Update gh workflows for complete release workflow

---

app/controllers/submissions/new.js
tests/unit/controllers/submissions/new-test.js

When a submission is canceled, check to ensure the submission has an ID before calling to delete it from the backend.

Fix submission workflow cancel bug

---

app/adapters/application.js
app/adapters/file.js
app/components/workflow-files/index.js
app/services/doi.js
tests/test-helper.js

Put CSRF tokens from cookies into headers.
This requires all the prs mentioned in https://github.com/eclipse-pass/pass-core/pull/90 in order to test.
Without the other prs the unit tests will succeed, but the acceptance tests will fail.

Handle CSRF tokens

---

.github/workflows/ci.yml
package.json

- this fixes an issue with concurrently where both the noserve and serve scripts were being run at the same time causing an error when we switched to pnpm
- the default setup in ember is what this PR proposes

fix: use default ember test scripts in package.json

---

app/components/submission-repo-details/index.js
app/models/deposit.js
tests/integration/components/submission-repo-details-test.js

If the deposit status is failed and `deposit.statusMessage` is defined, it will be included in the Deposit Status tooltip message.

Add deposit status message to deposit status tooltip

---

README.md

This PR adds the Guides and License sections in the pass-ui repository top level README.
Related to https://github.com/eclipse-pass/main/pull/1081. When merged PR 1081 will close the https://github.com/eclipse-pass/main/issues/1035; however these PRs can be merged in any order.

Add Guides and License section

---

Dockerfile

This PR updates the Dockerfile so the pass-ui docker container runs with the non-privileged nginx user.
Note that the base image was changed to nginxinc/nginx-unprivileged:1.27.3-alpine.  This is what I found was the suggested way for running the nginx docker container with a non-privileged user. (https://hub.docker.com/_/nginx Running nginx as a non-root user).  Also note the upgrade in nginx version to 1.27.3.
I have tested this locally in pass-docker and acceptance tests pass.  I also tested the config where custom branding is mounted.  L&F changed and tests passed.

Set USER in docker

---

app/components/workflow-metadata/index.js
app/services/doi.js
app/services/metadata-schema.js
tests/acceptance/nih-submission-test.js

The publication date formatting stored in the metadata must match what is expected by the data picker.
The error messages about missing metadata are now better formatted.
I was worried about  the publication date not being editable if it is not in the doi metadata since it is required. But despite it not seeming to be required, it is on every DOI I look at. And making a change so that missing values are editable also might be problematic.

Fix publication date parsing of doi metadata 

---

app/components/external-repo-review/index.js
app/components/submission-action-cell/index.js
app/components/workflow-basics/index.js
app/components/workflow-files/index.js
app/components/workflow-metadata/index.js
app/components/workflow-review/index.js
app/controllers/submissions/detail.js
app/controllers/submissions/new.js
app/controllers/submissions/new/files.js
app/controllers/submissions/new/repositories.js
app/index.html
app/services/error-handler.js
app/styles/app.css
ember-cli-build.js
package.json
pnpm-lock.yaml
tests/acceptance/nih-submission-test.js
tests/integration/components/workflow-metadata-test.js
tests/integration/components/workflow-review-test.js
tests/unit/controllers/submissions/detail-test.js
tests/unit/controllers/submissions/new-test.js
tests/unit/controllers/submissions/new/files-test.js
tests/unit/controllers/submissions/new/repositories-test.js

This PR upgrades and changes the way sweetalert2 is imported so that the CSP `unsafe-inline` directive is not needed.
Changes:
-Upgrade sweetalert2 to latest version
-Remove sweetalert2 link in index.html
-Import `'sweetalert2/dist/sweetalert2.js'` in component that uses `swal` so that the javascript is imported without the embedded CSS.
-app.import sweetalert2.css in `ember-cli-build.js`
-Update calls to `swal` to use new `swal.fire` function to open dialog
-Update use of `swal` mixin/queue to use new Queue.fire API.
Opened this pass-docker PR with changes to local_env CSP: https://github.com/eclipse-pass/pass-docker/pull/394
To test, build pass-ui and test in pass-docker as usual with local build.  
I also run acceptance-tests locally, and they passed.

Upgrade sweetalert2 and remove unsafe-inline requirement

---

app/controllers/grants/index.js
app/controllers/submissions/index.js
app/controllers/thanks.js
app/router.js
app/routes/check-session-route.js
app/services/error-handler.js
tests/unit/services/error-handler-test.js

This PR fixes a few issues with the UI rendering blank:
- Reload of page with query params such as filter on Submission page and refresh.
- In browser, enter valid path but invalid ID such as https://stage.pass.jhu.edu/app/submissions/999999.  Now shows 404 page.
- In browser, enter path like `/submissions/new/basicmmm` caused infinite page reload error.  Now shows 404 page.
- Other errors other than 401 and 403 on page load. Now shows dialog with error message.

Fix page reload blank render issues

---

app/components/workflow-review/index.js
app/controllers/submissions/detail.js

This PR fixes the bug where if a submission is only being deposited into PMC, the submit confirmation dialog will now work as expected.  It also has some refactoring to try to make the conditional logic try a bit easier to understand.
Good to test confirmation dialog on Workflow Review page on Submit button, and the Submit button on the Submission Details page in the proxy workflow request approval use case.

Fix submit confirmation bug

---

app/routes/submissions/detail.js

This fixes an issue found during testing.  Here is when the issue happened:
- Running pass-docker locally
- Login as nih-user
- Start new submission
- Submit for proxy for staff1 user
- Go all the way through and Request approval
- Go to Submissions page and click the submission title link to view the details page
- Refresh the browser, this is where there would be an infinite error issue.
The issue was the `submitter` was not included when getting the submission.

Fix infinite error load issue on proxy submission details refresh

---

app/components/grant-link-newtab-cell/index.hbs
app/components/grant-link-newtab-cell/index.js
app/components/grant-title-date-cell/index.hbs
app/components/grant-title-date-cell/index.js
app/components/submission-funding-table/index.hbs
app/components/workflow-grants/index.hbs
app/components/workflow-grants/index.js
app/controllers/grants/detail.js
tests/acceptance/nih-submission-test.js
tests/acceptance/proxy-submission-test.js

* Changes the grant links on the grant selection and selected grants tables in the workflow to open the grant details page in a new tab
* Refactors the grant selection table to have start/end dates in columns separated from the project name as well as the status in a new column
I'm planning to ignore the sonar qube failure. It is related to duplicated code in tests and is captured in https://github.com/eclipse-pass/main/issues/1177.

Refactor grant selection table to be more informative
